// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import 'package:test/test.dart';
import 'package:units/units.dart';

void main() {
    group('Angle Tests', () {
        test('Convert known Degrees to Radians', () {
            expect(Degrees.toRadians(98.8), closeTo(1.724385, 0.01));
            expect(Degrees.toRadians(8000.0), closeTo(139.6263, 0.01));
            expect(Degrees.toRadians(8.0), closeTo(0.139626, 0.01));
        });

        test('Convert known Degrees to Gradians', () {
            expect(Degrees.toGradians(123.0), closeTo(136.667, 0.01));
            expect(Degrees.toGradians(65.0), closeTo(72.2222, 0.01));
            expect(Degrees.toGradians(900.0), closeTo(1000.0, 0.01));
        });

        test('Convert known Degrees to Milliradians', () {
            expect(Degrees.toMilliradians(900.0), closeTo(15707.969, 0.01));
            expect(Degrees.toMilliradians(76.0), closeTo(1326.45, 0.01));
            expect(Degrees.toMilliradians(4.5), closeTo(78.5398, 0.01));
            expect(Degrees.toMilliradians(23333.11), closeTo(407239.5873, 0.01));
        });

        test('Convert known Degrees to Minute Of Arc', () {
            expect(Degrees.toMinuteOfArc(97.0), closeTo(5820.0, 0.01));
            expect(Degrees.toMinuteOfArc(8.65), closeTo(519.0, 0.01));
            expect(Degrees.toMinuteOfArc(12.0), closeTo(720.0, 0.01));
        });

        test('Convert known Degrees to Seconds Of Arc', () {
            expect(Degrees.toSecondsOfArc(12.0), closeTo(43200.0, 0.01));
            expect(Degrees.toSecondsOfArc(910.4), closeTo(3277440.0, 0.01));
            expect(Degrees.toSecondsOfArc(5.6), closeTo(20160.0, 0.01));
        });

        test('Convert known Gradians to Degrees', () {
            expect(Gradians.toDegrees(5.6), closeTo(5.04, 0.01));
            expect(Gradians.toDegrees(167.0), closeTo(150.3, 0.01));
            expect(Gradians.toDegrees(0.1), closeTo(0.09, 0.01));
        });

        test('Convert known Gradians to Radians', () {
            expect(Gradians.toRadians(67.9), closeTo(1.066571, 0.01));
            expect(Gradians.toRadians(8000.0), closeTo(125.6637, 0.01));
            expect(Gradians.toRadians(6.5), closeTo(0.102102, 0.01));
        });

        test('Convert known Gradians to Milliradians', () {
            expect(Gradians.toMilliradians(8.1), closeTo(127.2348, 0.01));
            expect(Gradians.toMilliradians(900.0), closeTo(14137.167, 0.01));
            expect(Gradians.toMilliradians(1902.5), closeTo(29884.4, 0.01));
        });

        test('Convert known Gradians to Minute Of Arc', () {
            expect(Gradians.toMinuteOfArc(80.9), closeTo(4368.6, 0.01));
            expect(Gradians.toMinuteOfArc(1678.0), closeTo(90612.0, 0.01));
            expect(Gradians.toMinuteOfArc(900.0), closeTo(48600.0, 0.01));
        });

        test('Convert known Gradians to Seconds Of Arc', () {
            expect(Gradians.toSecondsOfArc(0.9), closeTo(2916.0, 0.01));
            expect(Gradians.toSecondsOfArc(12.3), closeTo(39852.0, 0.01));
            expect(Gradians.toSecondsOfArc(5.1), closeTo(16524.0, 0.01));
        });

        test('Convert known Milliradians to Degrees', () {
            expect(Milliradians.toDegrees(5.9), closeTo(0.338045, 0.01));
            expect(Milliradians.toDegrees(109.0), closeTo(6.24524, 0.01));
            expect(Milliradians.toDegrees(7009.0), closeTo(401.5861, 0.01));
            expect(Milliradians.toDegrees(407239.5873), closeTo(23333.11, 0.01));
        });

        test('Convert known Milliradians to Radians', () {
            expect(Milliradians.toRadians(8011.0), closeTo(8.011, 0.01));
            expect(Milliradians.toRadians(7689.0), closeTo(7.689, 0.01));
            expect(Milliradians.toRadians(129.0), closeTo(0.129, 0.01));
        });

        test('Convert known Milliradians to Gradians', () {
            expect(Milliradians.toGradians(129.0), closeTo(8.2124, 0.01));
            expect(Milliradians.toGradians(800.0), closeTo(50.9296, 0.01));
            expect(Milliradians.toGradians(12.89), closeTo(0.8206029, 0.01));
        });

        test('Convert known Milliradians to Minute Of Arc', () {
            expect(Milliradians.toMinuteOfArc(12.0), closeTo(41.253, 0.01));
            expect(Milliradians.toMinuteOfArc(0.9), closeTo(3.09397, 0.01));
            expect(Milliradians.toMinuteOfArc(800.0), closeTo(2750.2, 0.01));
        });

        test('Convert known Milliradians to Seconds Of Arc', () {
            expect(Milliradians.toSecondsOfArc(67.0), closeTo(13819.742, 0.01));
            expect(Milliradians.toSecondsOfArc(900.0), closeTo(185638.32562238674, 0.01));
            expect(Milliradians.toSecondsOfArc(812.5), closeTo(167590.16, 0.01));
        });

        test('Convert known Minute Of Arc to Degrees', () {
            expect(MinuteOfArc.toDegrees(89.0), closeTo(1.48333, 0.01));
            expect(MinuteOfArc.toDegrees(160.5), closeTo(2.675, 0.01));
            expect(MinuteOfArc.toDegrees(0.9), closeTo(0.015, 0.01));
        });

        test('Convert known Minute Of Arc to Radians', () {
            expect(MinuteOfArc.toRadians(1790.0), closeTo(0.5206899, 0.01));
            expect(MinuteOfArc.toRadians(9999.0), closeTo(2.908591, 0.01));
            expect(MinuteOfArc.toRadians(12345.0), closeTo(3.5910149, 0.01));
        });

        test('Convert known Minute Of Arc to Gradians', () {
            expect(MinuteOfArc.toGradians(300.0), closeTo(5.55556, 0.01));
            expect(MinuteOfArc.toGradians(1009.0), closeTo(18.68519, 0.01));
            expect(MinuteOfArc.toGradians(6700.5), closeTo(124.083335, 0.01));
        });

        test('Convert known Minute Of Arc to Milliradians', () {
            expect(MinuteOfArc.toMilliradians(600.0), closeTo(174.533, 0.01));
            expect(MinuteOfArc.toMilliradians(90.7), closeTo(26.38356, 0.01));
            expect(MinuteOfArc.toMilliradians(1700.0), closeTo(494.51, 0.01));
        });

        test('Convert known Minute Of Arc to Seconds Of Arc', () {
            expect(MinuteOfArc.toSecondsOfArc(0.9), closeTo(54.0, 0.01));
            expect(MinuteOfArc.toSecondsOfArc(70.0), closeTo(4200.0, 0.01));
            expect(MinuteOfArc.toSecondsOfArc(901.6), closeTo(54096.0, 0.01));
        });

        test('Convert known Radians to Degrees', () {
            expect(Radians.toDegrees(4.5), closeTo(257.831, 0.01));
            expect(Radians.toDegrees(0.9), closeTo(51.5662, 0.01));
            expect(Radians.toDegrees(78.9), closeTo(4520.637, 0.01));
        });

        test('Convert known Radians to Gradians', () {
            expect(Radians.toGradians(5.0), closeTo(318.31, 0.01));
            expect(Radians.toGradians(0.9), closeTo(57.2958, 0.01));
            expect(Radians.toGradians(89.0), closeTo(5665.92, 0.01));
        });

        test('Convert known Radians to Milliradians', () {
            expect(Radians.toMilliradians(5.0), closeTo(5000.0, 0.01));
            expect(Radians.toMilliradians(0.13), closeTo(130.0, 0.01));
            expect(Radians.toMilliradians(0.13), closeTo(130.0, 0.01));
            expect(Radians.toMilliradians(89.1), closeTo(89100.0, 0.01));
        });

        test('Convert known Radians to Minute Of Arc', () {
            expect(Radians.toMinuteOfArc(6.0), closeTo(20626.480624709635, 0.01));
            expect(Radians.toMinuteOfArc(0.8), closeTo(2750.2, 0.01));
            expect(Radians.toMinuteOfArc(2.3), closeTo(7906.82, 0.01));
        });

        test('Convert known Radians to Seconds Of Arc', () {
            expect(Radians.toSecondsOfArc(0.8), closeTo(165011.84499767708, 0.01));
            expect(Radians.toSecondsOfArc(0.001), closeTo(206.26481, 0.01));
            expect(Radians.toSecondsOfArc(0.9), closeTo(185638.32562238674, 0.01));
        });

        test('Convert known Seconds Of Arc to Degrees', () {
            expect(SecondsOfArc.toDegrees(900.0), closeTo(0.25, 0.01));
            expect(SecondsOfArc.toDegrees(123.4), closeTo(0.034277778, 0.01));
            expect(SecondsOfArc.toDegrees(8000.0), closeTo(2.222222, 0.01));
        });

        test('Convert known Seconds Of Arc to Radians', () {
            expect(SecondsOfArc.toRadians(190000.0), closeTo(0.921145994, 0.01));
            expect(SecondsOfArc.toRadians(88990.0), closeTo(0.43143569, 0.01));
            expect(SecondsOfArc.toRadians(100000.0), closeTo(0.48481368, 0.01));
        });

        test('Convert known Seconds Of Arc to Gradians', () {
            expect(SecondsOfArc.toGradians(1000.0), closeTo(0.308642, 0.01));
            expect(SecondsOfArc.toGradians(809.0), closeTo(0.249691, 0.01));
            expect(SecondsOfArc.toGradians(1567.9), closeTo(0.483919761, 0.01));
        });

        test('Convert known Seconds Of Arc to Milliradians', () {
            expect(SecondsOfArc.toMilliradians(1234.0), closeTo(5.982601, 0.01));
            expect(SecondsOfArc.toMilliradians(909.0), closeTo(4.40696, 0.01));
            expect(SecondsOfArc.toMilliradians(190009.0), closeTo(921.189627, 0.01));
        });

        test('Convert known Seconds Of Arc to Minute Of Arc', () {
            expect(SecondsOfArc.toMinuteOfArc(100.0), closeTo(1.66667, 0.01));
            expect(SecondsOfArc.toMinuteOfArc(908.0), closeTo(15.1333, 0.01));
            expect(SecondsOfArc.toMinuteOfArc(8091.0), closeTo(134.85, 0.01));
        });

    });
}
