// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import 'package:test/test.dart';
import 'package:units/units.dart';

void main() {
    group('Energy Tests', () {
        test('Convert known Btu to Kilojoules', () {
            expect(Btu.toKilojoules(100.0), closeTo(105.506, 0.01));
            expect(Btu.toKilojoules(987.65), closeTo(1042.03, 0.01));
            expect(Btu.toKilojoules(555666.0), closeTo(586258.6917293, 0.01));
        });

        test('Convert known Btu to Kilocalories', () {
            expect(Btu.toKilocalories(67.9), closeTo(17.12196, 0.01));
            expect(Btu.toKilocalories(109.9), closeTo(27.712867639325825, 0.01));
            expect(Btu.toKilocalories(5000.0), closeTo(1260.8220036090, 0.01));
        });

        test('Convert known Btu to Joules', () {
            expect(Btu.toJoules(5.0), closeTo(5275.3, 0.01));
            expect(Btu.toJoules(912.9), closeTo(963164.274, 0.01));
            expect(Btu.toJoules(109.0), closeTo(115001.54, 0.01));
        });

        test('Convert known Btu to Calories', () {
            expect(Btu.toCalories(56.0), closeTo(14121.20644042079, 0.01));
            expect(Btu.toCalories(123.0), closeTo(31016.221288781402, 0.01));
            expect(Btu.toCalories(0.9), closeTo(226.9476, 0.01));
        });

        test('Convert known Btu to US Therms', () {
            expect(Btu.toUSTherms(12000.0), closeTo(0.120028657, 0.01));
            expect(Btu.toUSTherms(9876.5), closeTo(0.098788586, 0.01));
            expect(Btu.toUSTherms(666.999), closeTo(0.006671583, 0.01));
        });

        test('Convert known Btu to Watt Hours', () {
            expect(Btu.toWattHours(900.0), closeTo(263.764, 0.01));
            expect(Btu.toWattHours(125.7), closeTo(36.839034, 0.01));
            expect(Btu.toWattHours(0.99), closeTo(0.2901404, 0.01));
        });

        test('Convert known Btu to Kilowatt Hours', () {
            expect(Btu.toKilowattHours(9000.0), closeTo(2.63764, 0.01));
            expect(Btu.toKilowattHours(12345.0), closeTo(3.6179624, 0.01));
            expect(Btu.toKilowattHours(8090.8), closeTo(2.37117941, 0.01));
        });

        test('Convert known Btu to Foot Pounds', () {
            expect(Btu.toFootPounds(189.0), closeTo(147073.9409, 0.01));
            expect(Btu.toFootPounds(0.3), closeTo(233.451, 0.01));
            expect(Btu.toFootPounds(2.6), closeTo(2023.24, 0.01));
        });

        test('Convert known Btu to Electronvolts', () {
            expect(Btu.toElectronvolts(0.0000000789), closeTo(519567655294184.88, 0.01));
            expect(Btu.toElectronvolts(0.000001002), closeTo(6598311667994592.0, 0.01));
            expect(Btu.toElectronvolts(0.000000001), closeTo(6585141385224.14, 0.01));
        });

        test('Convert known Calories to Kilojoules', () {
            expect(Calories.toKilojoules(109.0), closeTo(0.456056, 0.01));
            expect(Calories.toKilojoules(12.3), closeTo(0.0514632, 0.01));
            expect(Calories.toKilojoules(9876.0), closeTo(41.32118, 0.01));
        });

        test('Convert known Calories to Kilocalories', () {
            expect(Calories.toKilocalories(900.0), closeTo(0.9, 0.01));
            expect(Calories.toKilocalories(1782.0), closeTo(1.782, 0.01));
            expect(Calories.toKilocalories(900800.0), closeTo(900.8, 0.01));
        });

        test('Convert known Calories to Joules', () {
            expect(Calories.toJoules(98.0), closeTo(410.032, 0.01));
            expect(Calories.toJoules(1.67), closeTo(6.98728, 0.01));
            expect(Calories.toJoules(55.0), closeTo(230.12, 0.01));
        });

        test('Convert known Calories to Btu', () {
            expect(Calories.toBtu(550.0), closeTo(2.18112, 0.01));
            expect(Calories.toBtu(1234.0), closeTo(4.893633, 0.01));
            expect(Calories.toBtu(900.9), closeTo(3.5726692, 0.01));
        });

        test('Convert known Calories to US Therms', () {
            expect(Calories.toUSTherms(9000000.0), closeTo(0.356995242, 0.01));
            expect(Calories.toUSTherms(12e6), closeTo(0.475993657, 0.01));
            expect(Calories.toUSTherms(100200300.0), closeTo(3.974558932, 0.01));
        });

        test('Convert known Calories to Watt Hours', () {
            expect(Calories.toWattHours(600.0), closeTo(0.697333, 0.01));
            expect(Calories.toWattHours(1234.5), closeTo(1.43476333, 0.01));
            expect(Calories.toWattHours(88.7), closeTo(0.1030891, 0.01));
        });

        test('Convert known Calories to Kilowatt Hours', () {
            expect(Calories.toKilowattHours(100900.0), closeTo(0.117268222, 0.01));
            expect(Calories.toKilowattHours(987654.0), closeTo(1.14787343, 0.01));
            expect(Calories.toKilowattHours(506012.0), closeTo(0.588098391, 0.01));
        });

        test('Convert known Calories to Foot Pounds', () {
            expect(Calories.toFootPounds(123.0), closeTo(379.573, 0.01));
            expect(Calories.toFootPounds(9.01), closeTo(27.8045, 0.01));
            expect(Calories.toFootPounds(2.8), closeTo(8.64069, 0.01));
        });

        test('Convert known Calories to Electronvolts', () {
            expect(Calories.toElectronvolts(0.0000091), closeTo(237800626261534.66, 0.01));
            expect(Calories.toElectronvolts(0.0008), closeTo(20905549561453600.0, 0.01));
            expect(Calories.toElectronvolts(0.00123), closeTo(32142282450734908.0, 0.01));
        });

        test('Convert known Electronvolts to Kilojoules', () {
            expect(Electronvolts.toKilojoules(123456789.0), closeTo(1.9779957413e-14, 0.01));
            expect(Electronvolts.toKilojoules(900900900.0), closeTo(1.4434023094e-13, 0.01));
            expect(Electronvolts.toKilojoules(123456789123456789.0), closeTo(1.977995743237493669e-5, 0.01));
        });

        test('Convert known Electronvolts to Kilocalories', () {
            expect(Electronvolts.toKilocalories(100200300400.0), closeTo(1.6053857310684e-11, 0.01));
            expect(Electronvolts.toKilocalories(123456789.0), closeTo(1.9779957413e-14, 0.01));
            expect(Electronvolts.toKilocalories(900800700600.0), closeTo(1.4432417722369e-10, 0.01));
        });

        test('Convert known Electronvolts to Joules', () {
            expect(Electronvolts.toJoules(123456789123.0), closeTo(1.9779957432302e-8, 0.01));
            expect(Electronvolts.toJoules(900800700600.0), closeTo(1.4432417722369e-7, 0.01));
            expect(Electronvolts.toJoules(999888777666.0), closeTo(1.601998367183e-7, 0.01));
        });

        test('Convert known Electronvolts to Btu', () {
            expect(Electronvolts.toBtu(100020003000100020003000.0), closeTo(15.188741377060267723, 0.01));
            expect(Electronvolts.toBtu(999888777666999888777666.0), closeTo(151.84014791315084381, 0.01));
            expect(Electronvolts.toBtu(12345678912341234567891234.0), closeTo(1874.7782293466862029, 0.01));
        });

        test('Convert known Electronvolts to Calories', () {
            expect(Electronvolts.toCalories(666333111999.0), closeTo(2.5515853167503e-8, 0.01));
            expect(Electronvolts.toCalories(999888777666555.0), closeTo(3.8288679904011702e-5, 0.01));
            expect(Electronvolts.toCalories(12345678901234.0), closeTo(4.727523282641506e-7, 0.01));
        });

        test('Convert known Electronvolts to US Therms', () {
            expect(Electronvolts.toUSTherms(666333111999.0), closeTo(1.0118737258101e-10, 0.01));
            expect(Electronvolts.toUSTherms(999888777666555.0), closeTo(1.5184014791308327e-7, 0.01));
            expect(Electronvolts.toUSTherms(12345678901234.0), closeTo(1.874778227659974e-9, 0.01));
        });

        test('Convert known Electronvolts to Watt Hours', () {
            expect(Electronvolts.toWattHours(100900700100.0), closeTo(4.490576030342e-12, 0.01));
            expect(Electronvolts.toWattHours(9000800070006000.0), closeTo(4.00579748289276988e-7, 0.01));
            expect(Electronvolts.toWattHours(12345678987654321.0), closeTo(5.494432653620188248e-7, 0.01));
        });

        test('Convert known Electronvolts to Kilowatt Hours', () {
            expect(Electronvolts.toKilowattHours(100900700100.0), closeTo(4.490576030342e-15, 0.01));
            expect(Electronvolts.toKilowattHours(999988887777.0), closeTo(4.4504410034909e-14, 0.01));
            expect(Electronvolts.toKilowattHours(12345678987654321.0), closeTo(5.494432653620187834e-10, 0.01));
        });

        test('Convert known Electronvolts to Foot Pounds', () {
            expect(Electronvolts.toFootPounds(100900700100.0), closeTo(1.1923484070355e-8, 0.01));
            expect(Electronvolts.toFootPounds(999988887777.0), closeTo(1.1816916594359e-7, 0.01));
            expect(Electronvolts.toFootPounds(12345678987654321.0), closeTo(0.0014588948005427860004, 0.01));
        });

        test('Convert known Foot Pounds to Kilojoules', () {
            expect(FootPounds.toKilojoules(190.0), closeTo(0.257605, 0.01));
            expect(FootPounds.toKilojoules(4.6), closeTo(0.00623676, 0.01));
            expect(FootPounds.toKilojoules(123.8), closeTo(0.16785026, 0.01));
        });

        test('Convert known Foot Pounds to Kilocalories', () {
            expect(FootPounds.toKilocalories(1999.0), closeTo(0.6477725, 0.01));
            expect(FootPounds.toKilocalories(890.8), closeTo(0.2886622, 0.01));
            expect(FootPounds.toKilocalories(12000.0), closeTo(3.8885792, 0.01));
        });

        test('Convert known Foot Pounds to Joules', () {
            expect(FootPounds.toJoules(190.0), closeTo(257.605, 0.01));
            expect(FootPounds.toJoules(23.4), closeTo(31.72614, 0.01));
            expect(FootPounds.toJoules(9.2), closeTo(12.4735, 0.01));
        });

        test('Convert known Foot Pounds to Btu', () {
            expect(FootPounds.toBtu(9000.0), closeTo(11.56561, 0.01));
            expect(FootPounds.toBtu(45.6), closeTo(0.05859908, 0.01));
            expect(FootPounds.toBtu(1996.0), closeTo(2.564995, 0.01));
        });

        test('Convert known Foot Pounds to Calories', () {
            expect(FootPounds.toCalories(123.0), closeTo(39.8579, 0.01));
            expect(FootPounds.toCalories(54.7), closeTo(17.72544, 0.01));
            expect(FootPounds.toCalories(109.2), closeTo(35.386071, 0.01));
        });

        test('Convert known Foot Pounds to US Therms', () {
            expect(FootPounds.toUSTherms(19000000.0), closeTo(0.24422111613, 0.01));
            expect(FootPounds.toUSTherms(1234567.0), closeTo(0.01586880688, 0.01));
            expect(FootPounds.toUSTherms(100200300.0), closeTo(1.28794890016, 0.01));
        });

        test('Convert known Foot Pounds to Watt Hours', () {
            expect(FootPounds.toWattHours(44.0), closeTo(0.0165711, 0.01));
            expect(FootPounds.toWattHours(9080.0), closeTo(3.419674, 0.01));
            expect(FootPounds.toWattHours(1200.0), closeTo(0.4519393, 0.01));
        });

        test('Convert known Foot Pounds to Kilowatt Hours', () {
            expect(FootPounds.toKilowattHours(900000.0), closeTo(0.338954487, 0.01));
            expect(FootPounds.toKilowattHours(100200.0), closeTo(0.0377369329, 0.01));
            expect(FootPounds.toKilowattHours(9876543.0), closeTo(3.719665074, 0.01));
        });

        test('Convert known Foot Pounds to Electronvolts', () {
            expect(FootPounds.toElectronvolts(0.00123), closeTo(10408691651641586.0, 0.01));
            expect(FootPounds.toElectronvolts(0.0009), closeTo(7616115842664575.0, 0.01));
            expect(FootPounds.toElectronvolts(0.00000888), closeTo(75145676314290.469, 0.01));
        });

        test('Convert known Joules to Kilojoules', () {
            expect(Joules.toKilojoules(790.0), closeTo(0.79, 0.01));
            expect(Joules.toKilojoules(800100.0), closeTo(800.1, 0.01));
            expect(Joules.toKilojoules(509.2), closeTo(0.5092, 0.01));
        });

        test('Convert known Joules to Kilocalories', () {
            expect(Joules.toKilocalories(790.0), closeTo(0.188815, 0.01));
            expect(Joules.toKilocalories(125.9), closeTo(0.030090822, 0.01));
            expect(Joules.toKilocalories(8000.0), closeTo(1.912046, 0.01));
        });

        test('Convert known Joules to Btu', () {
            expect(Joules.toBtu(500.0), closeTo(0.473909, 0.01));
            expect(Joules.toBtu(1910.0), closeTo(1.810331, 0.01));
            expect(Joules.toBtu(67000.1), closeTo(63.50384184, 0.01));
        });

        test('Convert known Joules to Calories', () {
            expect(Joules.toCalories(67.0), closeTo(16.0134, 0.01));
            expect(Joules.toCalories(909.0), closeTo(217.256, 0.01));
            expect(Joules.toCalories(190.0), closeTo(45.4111, 0.01));
        });

        test('Convert known Joules to US Therms', () {
            expect(Joules.toUSTherms(100090000.0), closeTo(0.948896667059, 0.01));
            expect(Joules.toUSTherms(55.7e6), closeTo(0.52806018938, 0.01));
            expect(Joules.toUSTherms(1234567890.0), closeTo(11.70423974501, 0.01));
        });

        test('Convert known Joules to Watt Hours', () {
            expect(Joules.toWattHours(56000.0), closeTo(15.555556, 0.01));
            expect(Joules.toWattHours(890.0), closeTo(0.247222, 0.01));
            expect(Joules.toWattHours(22001.0), closeTo(6.1113889, 0.01));
        });

        test('Convert known Joules to Kilowatt Hours', () {
            expect(Joules.toKilowattHours(560000.8), closeTo(0.1555557, 0.01));
            expect(Joules.toKilowattHours(1234567.0), closeTo(0.3429352778, 0.01));
            expect(Joules.toKilowattHours(900100.0), closeTo(0.250027778, 0.01));
        });

        test('Convert known Joules to Foot Pounds', () {
            expect(Joules.toFootPounds(900.0), closeTo(663.806, 0.01));
            expect(Joules.toFootPounds(10.2), closeTo(7.523134, 0.01));
            expect(Joules.toFootPounds(6.7), closeTo(4.94167, 0.01));
        });

        test('Convert known Joules to Electronvolts', () {
            expect(Joules.toElectronvolts(0.00000888), closeTo(55424602968504.0, 0.01));
            expect(Joules.toElectronvolts(0.00001234), closeTo(77020225296322.0, 0.01));
            expect(Joules.toElectronvolts(0.00000666), closeTo(41568452226378.0, 0.01));
        });

        test('Convert known Kilocalories to Kilojoules', () {
            expect(Kilocalories.toKilojoules(67.0), closeTo(280.328, 0.01));
            expect(Kilocalories.toKilojoules(4.5), closeTo(18.828, 0.01));
            expect(Kilocalories.toKilojoules(100.3), closeTo(419.6552, 0.01));
        });

        test('Convert known Kilocalories to Joules', () {
            expect(Kilocalories.toJoules(100.3), closeTo(419655.2, 0.01));
            expect(Kilocalories.toJoules(0.9), closeTo(3765.6, 0.01));
            expect(Kilocalories.toJoules(3.4), closeTo(14225.6, 0.01));
        });

        test('Convert known Kilocalories to Btu', () {
            expect(Kilocalories.toBtu(3.4), closeTo(13.4833, 0.01));
            expect(Kilocalories.toBtu(109.0), closeTo(432.2576846216055, 0.01));
            expect(Kilocalories.toBtu(22.89), closeTo(90.77411377053717, 0.01));
        });

        test('Convert known Kilocalories to Calories', () {
            expect(Kilocalories.toCalories(22.8), closeTo(22800.0, 0.01));
            expect(Kilocalories.toCalories(76.23), closeTo(76230.0, 0.01));
            expect(Kilocalories.toCalories(0.07), closeTo(70.0, 0.01));
        });

        test('Convert known Kilocalories to US Therms', () {
            expect(Kilocalories.toUSTherms(12345.0), closeTo(0.4896388, 0.01));
            expect(Kilocalories.toUSTherms(90002.0), closeTo(3.5700317, 0.01));
            expect(Kilocalories.toUSTherms(180180.0), closeTo(7.14704457, 0.01));
        });

        test('Convert known Kilocalories to Watt Hours', () {
            expect(Kilocalories.toWattHours(89.0), closeTo(103.438, 0.01));
            expect(Kilocalories.toWattHours(23.6), closeTo(27.42844, 0.01));
            expect(Kilocalories.toWattHours(0.9), closeTo(1.046, 0.01));
        });

        test('Convert known Kilocalories to Kilowatt Hours', () {
            expect(Kilocalories.toKilowattHours(456.0), closeTo(0.529973, 0.01));
            expect(Kilocalories.toKilowattHours(1090.8), closeTo(1.267752, 0.01));
            expect(Kilocalories.toKilowattHours(567.1), closeTo(0.65909622, 0.01));
        });

        test('Convert known Kilocalories to Foot Pounds', () {
            expect(Kilocalories.toFootPounds(109.0), closeTo(336369.64, 0.01));
            expect(Kilocalories.toFootPounds(0.5), closeTo(1542.98, 0.01));
            expect(Kilocalories.toFootPounds(2.4), closeTo(7406.3, 0.01));
        });

        test('Convert known Kilocalories to Electronvolts', () {
            expect(Kilocalories.toElectronvolts(0.0000000666), closeTo(1740388069688132.2, 0.01));
            expect(Kilocalories.toElectronvolts(0.000002), closeTo(52263905996640608.0, 0.01));
            expect(Kilocalories.toElectronvolts(0.000000999), closeTo(26105821045321988.0, 0.01));
        });

        test('Convert known Kilojoules to Kilocalories', () {
            expect(Kilojoules.toKilocalories(199.0), closeTo(47.5621, 0.01));
            expect(Kilojoules.toKilocalories(0.67), closeTo(0.1601338, 0.01));
            expect(Kilojoules.toKilocalories(4.7), closeTo(1.12333, 0.01));
        });

        test('Convert known Kilojoules to Joules', () {
            expect(Kilojoules.toJoules(4.7), closeTo(4700.0, 0.01));
            expect(Kilojoules.toJoules(7.8), closeTo(7800.0, 0.01));
            expect(Kilojoules.toJoules(1800.0), closeTo(1800000.0, 0.01));
        });

        test('Convert known Kilojoules to Btu', () {
            expect(Kilojoules.toBtu(1800.0), closeTo(1706.070, 0.01));
            expect(Kilojoules.toBtu(1.4), closeTo(1.32694, 0.01));
            expect(Kilojoules.toBtu(89.2), closeTo(84.54529, 0.01));
        });

        test('Convert known Kilojoules to Calories', () {
            expect(Kilojoules.toCalories(67.0), closeTo(16013.381899, 0.01));
            expect(Kilojoules.toCalories(1.4), closeTo(334.608, 0.01));
            expect(Kilojoules.toCalories(87.0), closeTo(20793.5, 0.01));
        });

        test('Convert known Kilojoules to US Therms', () {
            expect(Kilojoules.toUSTherms(123456.0), closeTo(1.17041649, 0.01));
            expect(Kilojoules.toUSTherms(88000.0), closeTo(0.83427822, 0.01));
            expect(Kilojoules.toUSTherms(9000.0), closeTo(0.08532391, 0.01));
        });

        test('Convert known Kilojoules to Watt Hours', () {
            expect(Kilojoules.toWattHours(98000.0), closeTo(27222.222, 0.01));
            expect(Kilojoules.toWattHours(1.5), closeTo(0.416667, 0.01));
            expect(Kilojoules.toWattHours(67.9), closeTo(18.86111, 0.01));
        });

        test('Convert known Kilojoules to Kilowatt Hours', () {
            expect(Kilojoules.toKilowattHours(8000.0), closeTo(2.222222, 0.01));
            expect(Kilojoules.toKilowattHours(67.99), closeTo(0.018886111, 0.01));
            expect(Kilojoules.toKilowattHours(406.8), closeTo(0.113, 0.01));
        });

        test('Convert known Kilojoules to Foot Pounds', () {
            expect(Kilojoules.toFootPounds(100.9), closeTo(74420.00579, 0.01));
            expect(Kilojoules.toFootPounds(2.4), closeTo(1770.15, 0.01));
            expect(Kilojoules.toFootPounds(0.9), closeTo(663.806, 0.01));
        });

        test('Convert known Kilojoules to Electronvolts', () {
            expect(Kilojoules.toElectronvolts(0.000000999), closeTo(6235268234766989.0, 0.01));
            expect(Kilojoules.toElectronvolts(0.0000002), closeTo(1248301948902300.0, 0.01));
            expect(Kilojoules.toElectronvolts(0.00567), closeTo(3.5389360251380204E+19, 0.01));
        });

        test('Convert known Kilowatt Hours to Kilojoules', () {
            expect(KilowattHours.toKilojoules(0.6), closeTo(2160.0, 0.01));
            expect(KilowattHours.toKilojoules(134.0), closeTo(482400.0, 0.01));
            expect(KilowattHours.toKilojoules(45.6), closeTo(164160.0, 0.01));
        });

        test('Convert known Kilowatt Hours to Kilocalories', () {
            expect(KilowattHours.toKilocalories(45.6), closeTo(39235.1976, 0.01));
            expect(KilowattHours.toKilocalories(12.0), closeTo(10325.052, 0.01));
            expect(KilowattHours.toKilocalories(0.4), closeTo(344.168, 0.01));
        });

        test('Convert known Kilowatt Hours to Joules', () {
            expect(KilowattHours.toJoules(0.01), closeTo(36000.0, 0.01));
            expect(KilowattHours.toJoules(0.009), closeTo(32400.0, 0.01));
            expect(KilowattHours.toJoules(2.0), closeTo(7.2e+6, 0.01));
        });

        test('Convert known Kilowatt Hours to Btu', () {
            expect(KilowattHours.toBtu(2.0), closeTo(6824.28, 0.01));
            expect(KilowattHours.toBtu(0.7), closeTo(2388.4979, 0.01));
            expect(KilowattHours.toBtu(0.02), closeTo(68.24283, 0.01));
        });

        test('Convert known Kilowatt Hours to Calories', () {
            expect(KilowattHours.toCalories(0.1), closeTo(86042.1, 0.01));
            expect(KilowattHours.toCalories(0.07), closeTo(60229.47, 0.01));
            expect(KilowattHours.toCalories(0.0123), closeTo(10583.174, 0.01));
        });

        test('Convert known Kilowatt Hours to US Therms', () {
            expect(KilowattHours.toUSTherms(5.0), closeTo(0.170648, 0.01));
            expect(KilowattHours.toUSTherms(234.0), closeTo(7.98632, 0.01));
            expect(KilowattHours.toUSTherms(1001.0), closeTo(34.16369, 0.01));
        });

        test('Convert known Kilowatt Hours to Watt Hours', () {
            expect(KilowattHours.toWattHours(123.0), closeTo(123000.0, 0.01));
            expect(KilowattHours.toWattHours(98.4), closeTo(98400.0, 0.01));
            expect(KilowattHours.toWattHours(1.6), closeTo(1600.0, 0.01));
        });

        test('Convert known Kilowatt Hours to Foot Pounds', () {
            expect(KilowattHours.toFootPounds(0.001), closeTo(2655.196219, 0.01));
            expect(KilowattHours.toFootPounds(0.09), closeTo(238967.6597, 0.01));
            expect(KilowattHours.toFootPounds(0.0006), closeTo(1593.1177314, 0.01));
        });

        test('Convert known Kilowatt Hours to Electronvolts', () {
            expect(KilowattHours.toElectronvolts(0.000008), closeTo(179755440000000000000.0, 0.01));
            expect(KilowattHours.toElectronvolts(0.0000000128), closeTo(2.8760870400000003E+17, 0.01));
            expect(KilowattHours.toElectronvolts(0.0000000001), closeTo(2246943000000000.2, 0.01));
        });

        test('Convert known US Therms to Kilojoules', () {
            expect(USTherms.toKilojoules(0.009), closeTo(949.3236, 0.01));
            expect(USTherms.toKilojoules(3.0), closeTo(316440.12, 0.01));
            expect(USTherms.toKilojoules(1.9), closeTo(200412.075, 0.01));
        });

        test('Convert known US Therms to Kilocalories', () {
            expect(USTherms.toKilocalories(1.1), closeTo(27731.484079398004, 0.01));
            expect(USTherms.toKilocalories(0.04), closeTo(1008.417, 0.01));
            expect(USTherms.toKilocalories(0.0123), closeTo(310.088174, 0.01));
        });

        test('Convert known US Therms to Joules', () {
            expect(USTherms.toJoules(0.008), closeTo(843843.2, 0.01));
            expect(USTherms.toJoules(3.4e-6), closeTo(358.633, 0.01));
            expect(USTherms.toJoules(0.00678), closeTo(715157.112, 0.01));
        });

        test('Convert known US Therms to Btu', () {
            expect(USTherms.toBtu(0.00666), closeTo(665.8409891, 0.01));
            expect(USTherms.toBtu(2.0), closeTo(199952.249, 0.01));
            expect(USTherms.toBtu(0.9), closeTo(89978.51204, 0.01));
        });

        test('Convert known US Therms to Calories', () {
            expect(USTherms.toCalories(0.003), closeTo(75631.262, 0.01));
            expect(USTherms.toCalories(6.8e-3), closeTo(171430.856, 0.01));
            expect(USTherms.toCalories(0.0008), closeTo(20168.3365, 0.01));
        });

        test('Convert known US Therms to Watt Hours', () {
            expect(USTherms.toWattHours(6.0), closeTo(175800.59, 0.01));
            expect(USTherms.toWattHours(1.9), closeTo(55670.189, 0.01));
            expect(USTherms.toWattHours(0.07), closeTo(2051.008, 0.01));
        });

        test('Convert known US Therms to Kilowatt Hours', () {
            expect(USTherms.toKilowattHours(0.9), closeTo(26.3701, 0.01));
            expect(USTherms.toKilowattHours(7.9), closeTo(231.471, 0.01));
            expect(USTherms.toKilowattHours(1.4), closeTo(41.0202, 0.01));
        });

        test('Convert known US Therms to Foot Pounds', () {
            expect(USTherms.toFootPounds(0.009), closeTo(700352.43389267, 0.01));
            expect(USTherms.toFootPounds(0.02), closeTo(1556338.74198, 0.01));
            expect(USTherms.toFootPounds(0.0003), closeTo(23345.081129, 0.01));
        });

        test('Convert known US Therms to Electronvolts', () {
            expect(USTherms.toElectronvolts(0.0000009), closeTo(592520940098199000000.0, 0.01));
            expect(USTherms.toElectronvolts(0.000000001339), closeTo(8.815394875460983E+17, 0.01));
            expect(USTherms.toElectronvolts(0.0000000000666), closeTo(43846549567266728.0, 0.01));
        });

        test('Convert known Watt Hours to Kilojoules', () {
            expect(WattHours.toKilojoules(1.6), closeTo(5.76, 0.01));
            expect(WattHours.toKilojoules(67.0), closeTo(241.2, 0.01));
            expect(WattHours.toKilojoules(8.12), closeTo(29.232, 0.01));
        });

        test('Convert known Watt Hours to Kilocalories', () {
            expect(WattHours.toKilocalories(8.12), closeTo(6.986616, 0.01));
            expect(WattHours.toKilocalories(170.0), closeTo(146.272, 0.01));
            expect(WattHours.toKilocalories(19.2), closeTo(16.52008, 0.01));
        });

        test('Convert known Watt Hours to Joules', () {
            expect(WattHours.toJoules(6.7), closeTo(24120.0, 0.01));
            expect(WattHours.toJoules(12.34), closeTo(44424.0, 0.01));
            expect(WattHours.toJoules(0.09), closeTo(324.0, 0.01));
        });

        test('Convert known Watt Hours to Btu', () {
            expect(WattHours.toBtu(34.0), closeTo(116.013, 0.01));
            expect(WattHours.toBtu(179.2), closeTo(611.45578, 0.01));
            expect(WattHours.toBtu(0.9), closeTo(3.07093, 0.01));
        });

        test('Convert known Watt Hours to Calories', () {
            expect(WattHours.toCalories(0.2), closeTo(172.084, 0.01));
            expect(WattHours.toCalories(0.09), closeTo(77.43786, 0.01));
            expect(WattHours.toCalories(12.0), closeTo(10325.06754, 0.01));
        });

        test('Convert known Watt Hours to US Therms', () {
            expect(WattHours.toUSTherms(1090.0), closeTo(0.03720122, 0.01));
            expect(WattHours.toUSTherms(49990.0), closeTo(1.7061369, 0.01));
            expect(WattHours.toUSTherms(900800.0), closeTo(30.7439107, 0.01));
        });

        test('Convert known Watt Hours to Kilowatt Hours', () {
            expect(WattHours.toKilowattHours(98.0), closeTo(0.098, 0.01));
            expect(WattHours.toKilowattHours(12.5), closeTo(0.0125, 0.01));
            expect(WattHours.toKilowattHours(0.6), closeTo(0.0006, 0.01));
        });

        test('Convert known Watt Hours to Foot Pounds', () {
            expect(WattHours.toFootPounds(1.5), closeTo(3982.829, 0.01));
            expect(WattHours.toFootPounds(0.3), closeTo(796.567, 0.01));
            expect(WattHours.toFootPounds(90.1), closeTo(239235.3219, 0.01));
        });

        test('Convert known Watt Hours to Electronvolts', () {
            expect(WattHours.toElectronvolts(0.0000000000666), closeTo(1496463565615.39, 0.01));
            expect(WattHours.toElectronvolts(0.000000008), closeTo(179755383257104.03, 0.01));
            expect(WattHours.toElectronvolts(0.0000123), closeTo(2.7637390175779744E+17, 0.01));
        });

    });
}
