// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import 'package:test/test.dart';
import 'package:conversion_units/conversion_units.dart';

void main() {
  group('Power Tests', () {
    test('Convert known Mechanical Horse Power to Metric Horse Power', () {
      expect(MechanicalHorsePower.toMetricHorsePower(65.0971),
          closeTo(65.9999749, 0.01));
      expect(MechanicalHorsePower.toMetricHorsePower(121.317),
          closeTo(122.9996, 0.01));
      expect(MechanicalHorsePower.toMetricHorsePower(86.7962),
          closeTo(88.0, 0.01));
    });

    test('Convert known Metric Horse Power to Mechanical Horse Power', () {
      expect(MetricHorsePower.toMechanicalHorsePower(126.734),
          closeTo(125.0, 0.01));
      expect(MetricHorsePower.toMechanicalHorsePower(91.2483),
          closeTo(90.0, 0.01));
      expect(MetricHorsePower.toMechanicalHorsePower(425.825),
          closeTo(419.9997, 0.01));
    });
  });
}
