// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

import 'package:test/test.dart';
import 'package:units/units.dart';

void main() {
    group('Pressure Tests', () {
        test('Convert known Atmospheres to Bars', () {
            expect(Atmospheres.toBars(6.0), closeTo(6.0795, 0.01));
            expect(Atmospheres.toBars(1.2), closeTo(1.2159, 0.01));
            expect(Atmospheres.toBars(0.8), closeTo(0.8106, 0.01));
        });

        test('Convert known Atmospheres to Pascals', () {
            expect(Atmospheres.toPascals(0.8), closeTo(81060.0, 0.01));
            expect(Atmospheres.toPascals(1.2), closeTo(121590.0, 0.01));
            expect(Atmospheres.toPascals(0.45), closeTo(45596.25, 0.01));
        });

        test('Convert known Atmospheres to Torrs', () {
            expect(Atmospheres.toTorrs(0.45), closeTo(342.0, 0.01));
            expect(Atmospheres.toTorrs(1.2), closeTo(912.0, 0.01));
            expect(Atmospheres.toTorrs(6.0), closeTo(4560.0, 0.01));
        });

        test('Convert known Atmospheres to Psi', () {
            expect(Atmospheres.toPsi(6.0), closeTo(88.1757, 0.01));
            expect(Atmospheres.toPsi(0.4), closeTo(5.87838, 0.01));
            expect(Atmospheres.toPsi(1.2), closeTo(17.6351, 0.01));
        });

        test('Convert known Bars to Atmospheres', () {
            expect(Bars.toAtmospheres(800.0), closeTo(789.539, 0.01));
            expect(Bars.toAtmospheres(123.0), closeTo(121.392, 0.01));
            expect(Bars.toAtmospheres(89.0), closeTo(87.8362, 0.01));
        });

        test('Convert known Bars to Pascals', () {
            expect(Bars.toPascals(0.89), closeTo(89000.0, 0.01));
            expect(Bars.toPascals(0.01), closeTo(1000.0, 0.01));
            expect(Bars.toPascals(0.123), closeTo(12300.0, 0.01));
        });

        test('Convert known Bars to Torrs', () {
            expect(Bars.toTorrs(0.123), closeTo(92.257587, 0.01));
            expect(Bars.toTorrs(2.0), closeTo(1500.12, 0.01));
            expect(Bars.toTorrs(8.9), closeTo(6675.55, 0.01));
        });

        test('Convert known Bars to Psi', () {
            expect(Bars.toPsi(8.1), closeTo(117.481, 0.01));
            expect(Bars.toPsi(1001.0), closeTo(14518.29290, 0.01));
            expect(Bars.toPsi(6.0), closeTo(87.0226, 0.01));
        });

        test('Convert known Pascals to Atmospheres', () {
            expect(Pascals.toAtmospheres(90000.0), closeTo(0.88823094, 0.01));
            expect(Pascals.toAtmospheres(1234567.0), closeTo(12.18422897, 0.01));
            expect(Pascals.toAtmospheres(204060.0), closeTo(2.01391562, 0.01));
        });

        test('Convert known Pascals to Bars', () {
            expect(Pascals.toBars(10000.0), closeTo(0.1, 0.01));
            expect(Pascals.toBars(12345.0), closeTo(0.12345, 0.01));
            expect(Pascals.toBars(80000.0), closeTo(0.8, 0.01));
        });

        test('Convert known Pascals to Torrs', () {
            expect(Pascals.toTorrs(80000.0), closeTo(600.04935, 0.01));
            expect(Pascals.toTorrs(1234.0), closeTo(9.255761, 0.01));
            expect(Pascals.toTorrs(80.0), closeTo(0.600049, 0.01));
        });

        test('Convert known Pascals to Psi', () {
            expect(Pascals.toPsi(800.0), closeTo(0.11603, 0.01));
            expect(Pascals.toPsi(8670.0), closeTo(1.257477, 0.01));
            expect(Pascals.toPsi(1000.0), closeTo(0.145038, 0.01));
        });

        test('Convert known Psi to Bars', () {
            expect(Psi.toBars(900.0), closeTo(62.0528, 0.01));
            expect(Psi.toBars(134.0), closeTo(9.23897, 0.01));
            expect(Psi.toBars(111.2), closeTo(7.6669701, 0.01));
        });

        test('Convert known Psi to Pascals', () {
            expect(Psi.toPascals(0.9), closeTo(6205.28, 0.01));
            expect(Psi.toPascals(0.03), closeTo(206.8427, 0.01));
            expect(Psi.toPascals(2.0), closeTo(13789.5, 0.01));
        });

        test('Convert known Psi to Atmospheres', () {
            expect(Psi.toAtmospheres(2.0), closeTo(0.136092, 0.01));
            expect(Psi.toAtmospheres(109.0), closeTo(7.41701, 0.01));
            expect(Psi.toAtmospheres(8.0), closeTo(0.544368, 0.01));
        });

        test('Convert known Psi to Torrs', () {
            expect(Psi.toTorrs(6.0), closeTo(310.29, 0.01));
            expect(Psi.toTorrs(3.4), closeTo(175.831, 0.01));
            expect(Psi.toTorrs(0.5), closeTo(25.8575, 0.01));
        });

        test('Convert known Torrs to Bars', () {
            expect(Torrs.toBars(100.0), closeTo(0.133322, 0.01));
            expect(Torrs.toBars(9000.1), closeTo(11.9991465, 0.01));
            expect(Torrs.toBars(1234.0), closeTo(1.645198, 0.01));
        });

        test('Convert known Torrs to Pascals', () {
            expect(Torrs.toPascals(190.0), closeTo(25331.2499, 0.01));
            expect(Torrs.toPascals(6.5), closeTo(866.595, 0.01));
            expect(Torrs.toPascals(3.4), closeTo(453.296, 0.01));
        });

        test('Convert known Torrs to Atmospheres', () {
            expect(Torrs.toAtmospheres(5678.0), closeTo(7.471053, 0.01));
            expect(Torrs.toAtmospheres(100.0), closeTo(0.131579, 0.01));
            expect(Torrs.toAtmospheres(4509.0), closeTo(5.932895, 0.01));
        });

        test('Convert known Torrs to Psi', () {
            expect(Torrs.toPsi(4500.0), closeTo(87.01549, 0.01));
            expect(Torrs.toPsi(1234.0), closeTo(23.86158, 0.01));
            expect(Torrs.toPsi(900.0), closeTo(17.4031, 0.01));
        });

    });
}
