name: conversion_units
description: Unit of measurements conversions. Convert between various units 
version: 0.1.7
homepage: https://github.com/putridparrot/DartUnits

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1