// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Acres {
	static double toSquareKilometres(double value) =>
		value / 247.105;
	static double toSquareMetres(double value) =>
		value * 4046.86;
	static double toSquareMiles(double value) =>
		value / 640.0;
	static double toSquareYards(double value) =>
		value * 4840.0;
	static double toSquareFeet(double value) =>
		value * 43560.0;
	static double toSquareInches(double value) =>
		value * 6272640.0;
	static double toHectares(double value) =>
		value / 2.4710538146717;
}

class Hectares {
	static double toSquareKilometres(double value) =>
		value / 100.0;
	static double toSquareMetres(double value) =>
		value * 10000.0;
	static double toSquareMiles(double value) =>
		value / 258.99881103;
	static double toSquareYards(double value) =>
		value * 11959.900463011;
	static double toSquareFeet(double value) =>
		value * 107639.0;
	static double toSquareInches(double value) =>
		value * 15500031.0;
	static double toAcres(double value) =>
		value * 2.4710538146717;
}

class SquareFeet {
	static double toSquareKilometres(double value) =>
		value / 10763910.41671;
	static double toSquareMetres(double value) =>
		value / 10.76391042;
	static double toSquareMiles(double value) =>
		value / 27878400.0;
	static double toSquareYards(double value) =>
		value / 9.0;
	static double toSquareInches(double value) =>
		value * 144.0;
	static double toHectares(double value) =>
		value / 107639.0;
	static double toAcres(double value) =>
		value / 43560.0;
}

class SquareInches {
	static double toSquareKilometres(double value) =>
		value / 1550003100.00;
	static double toSquareMetres(double value) =>
		value / 1550.0;
	static double toSquareMiles(double value) =>
		value / 4014489600.0;
	static double toSquareYards(double value) =>
		value / 1296.0;
	static double toSquareFeet(double value) =>
		value / 144.0;
	static double toHectares(double value) =>
		value / 15500031.0;
	static double toAcres(double value) =>
		value / 6272640.0;
}

class SquareKilometres {
	static double toSquareMetres(double value) =>
		value * 1e+6;
	static double toSquareMiles(double value) =>
		value / 2.58999;
	static double toSquareYards(double value) =>
		value * 1195990.05;
	static double toSquareFeet(double value) =>
		value * 10763910.41671;
	static double toSquareInches(double value) =>
		value * 1550003100.00;
	static double toHectares(double value) =>
		value * 100.0;
	static double toAcres(double value) =>
		value * 247.105;
}

class SquareMetres {
	static double toSquareKilometres(double value) =>
		value / 1e+6;
	static double toSquareMiles(double value) =>
		value / 2589988.10;
	static double toSquareYards(double value) =>
		value * 1.1959900463;
	static double toSquareFeet(double value) =>
		value * 10.76391042;
	static double toSquareInches(double value) =>
		value * 1550.0;
	static double toHectares(double value) =>
		value / 10000.0;
	static double toAcres(double value) =>
		value / 4046.86;
}

class SquareMiles {
	static double toSquareKilometres(double value) =>
		value * 2.58999;
	static double toSquareMetres(double value) =>
		value * 2589988.10;
	static double toSquareYards(double value) =>
		value * 3097600.0;
	static double toSquareFeet(double value) =>
		value * 27878400.0;
	static double toSquareInches(double value) =>
		value * 4014489600.0;
	static double toHectares(double value) =>
		value * 258.99881103;
	static double toAcres(double value) =>
		value * 640.0;
}

class SquareYards {
	static double toSquareKilometres(double value) =>
		value / 1195990.05;
	static double toSquareMetres(double value) =>
		value / 1.1959900463;
	static double toSquareMiles(double value) =>
		value / 3097600.0;
	static double toSquareFeet(double value) =>
		value * 9.0;
	static double toSquareInches(double value) =>
		value * 1296.0;
	static double toHectares(double value) =>
		value / 11959.900463011;
	static double toAcres(double value) =>
		value / 4840.0;
}
