// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Acres conversion functions
class Acres {
  Acres._() {}

  /// Converts the supplied Acres value to Square Kilometres
  static double toSquareKilometres(double value) => value / 247.105;

  /// Converts the supplied Acres value to Square Metres
  static double toSquareMetres(double value) => value * 4046.86;

  /// Converts the supplied Acres value to Square Miles
  static double toSquareMiles(double value) => value / 640.0;

  /// Converts the supplied Acres value to Square Yards
  static double toSquareYards(double value) => value * 4840.0;

  /// Converts the supplied Acres value to Square Feet
  static double toSquareFeet(double value) => value * 43560.0;

  /// Converts the supplied Acres value to Square Inches
  static double toSquareInches(double value) => value * 6272640.0;

  /// Converts the supplied Acres value to Hectares
  static double toHectares(double value) => value / 2.4710538146717;
}

/// Hectares conversion functions
class Hectares {
  Hectares._() {}

  /// Converts the supplied Hectares value to Square Kilometres
  static double toSquareKilometres(double value) => value / 100.0;

  /// Converts the supplied Hectares value to Square Metres
  static double toSquareMetres(double value) => value * 10000.0;

  /// Converts the supplied Hectares value to Square Miles
  static double toSquareMiles(double value) => value / 258.99881103;

  /// Converts the supplied Hectares value to Square Yards
  static double toSquareYards(double value) => value * 11959.900463011;

  /// Converts the supplied Hectares value to Square Feet
  static double toSquareFeet(double value) => value * 107639.0;

  /// Converts the supplied Hectares value to Square Inches
  static double toSquareInches(double value) => value * 15500031.0;

  /// Converts the supplied Hectares value to Acres
  static double toAcres(double value) => value * 2.4710538146717;
}

/// Square Feet conversion functions
class SquareFeet {
  SquareFeet._() {}

  /// Converts the supplied Square Feet value to Square Kilometres
  static double toSquareKilometres(double value) => value / 10763910.41671;

  /// Converts the supplied Square Feet value to Square Metres
  static double toSquareMetres(double value) => value / 10.76391042;

  /// Converts the supplied Square Feet value to Square Miles
  static double toSquareMiles(double value) => value / 27878400.0;

  /// Converts the supplied Square Feet value to Square Yards
  static double toSquareYards(double value) => value / 9.0;

  /// Converts the supplied Square Feet value to Square Inches
  static double toSquareInches(double value) => value * 144.0;

  /// Converts the supplied Square Feet value to Hectares
  static double toHectares(double value) => value / 107639.0;

  /// Converts the supplied Square Feet value to Acres
  static double toAcres(double value) => value / 43560.0;
}

/// Square Inches conversion functions
class SquareInches {
  SquareInches._() {}

  /// Converts the supplied Square Inches value to Square Kilometres
  static double toSquareKilometres(double value) => value / 1550003100.00;

  /// Converts the supplied Square Inches value to Square Metres
  static double toSquareMetres(double value) => value / 1550.0;

  /// Converts the supplied Square Inches value to Square Miles
  static double toSquareMiles(double value) => value / 4014489600.0;

  /// Converts the supplied Square Inches value to Square Yards
  static double toSquareYards(double value) => value / 1296.0;

  /// Converts the supplied Square Inches value to Square Feet
  static double toSquareFeet(double value) => value / 144.0;

  /// Converts the supplied Square Inches value to Hectares
  static double toHectares(double value) => value / 15500031.0;

  /// Converts the supplied Square Inches value to Acres
  static double toAcres(double value) => value / 6272640.0;
}

/// Square Kilometres conversion functions
class SquareKilometres {
  SquareKilometres._() {}

  /// Converts the supplied Square Kilometres value to Square Metres
  static double toSquareMetres(double value) => value * 1e+6;

  /// Converts the supplied Square Kilometres value to Square Miles
  static double toSquareMiles(double value) => value / 2.58999;

  /// Converts the supplied Square Kilometres value to Square Yards
  static double toSquareYards(double value) => value * 1195990.05;

  /// Converts the supplied Square Kilometres value to Square Feet
  static double toSquareFeet(double value) => value * 10763910.41671;

  /// Converts the supplied Square Kilometres value to Square Inches
  static double toSquareInches(double value) => value * 1550003100.00;

  /// Converts the supplied Square Kilometres value to Hectares
  static double toHectares(double value) => value * 100.0;

  /// Converts the supplied Square Kilometres value to Acres
  static double toAcres(double value) => value * 247.105;
}

/// Square Metres conversion functions
class SquareMetres {
  SquareMetres._() {}

  /// Converts the supplied Square Metres value to Square Kilometres
  static double toSquareKilometres(double value) => value / 1e+6;

  /// Converts the supplied Square Metres value to Square Miles
  static double toSquareMiles(double value) => value / 2589988.10;

  /// Converts the supplied Square Metres value to Square Yards
  static double toSquareYards(double value) => value * 1.1959900463;

  /// Converts the supplied Square Metres value to Square Feet
  static double toSquareFeet(double value) => value * 10.76391042;

  /// Converts the supplied Square Metres value to Square Inches
  static double toSquareInches(double value) => value * 1550.0;

  /// Converts the supplied Square Metres value to Hectares
  static double toHectares(double value) => value / 10000.0;

  /// Converts the supplied Square Metres value to Acres
  static double toAcres(double value) => value / 4046.86;
}

/// Square Miles conversion functions
class SquareMiles {
  SquareMiles._() {}

  /// Converts the supplied Square Miles value to Square Kilometres
  static double toSquareKilometres(double value) => value * 2.58999;

  /// Converts the supplied Square Miles value to Square Metres
  static double toSquareMetres(double value) => value * 2589988.10;

  /// Converts the supplied Square Miles value to Square Yards
  static double toSquareYards(double value) => value * 3097600.0;

  /// Converts the supplied Square Miles value to Square Feet
  static double toSquareFeet(double value) => value * 27878400.0;

  /// Converts the supplied Square Miles value to Square Inches
  static double toSquareInches(double value) => value * 4014489600.0;

  /// Converts the supplied Square Miles value to Hectares
  static double toHectares(double value) => value * 258.99881103;

  /// Converts the supplied Square Miles value to Acres
  static double toAcres(double value) => value * 640.0;
}

/// Square Yards conversion functions
class SquareYards {
  SquareYards._() {}

  /// Converts the supplied Square Yards value to Square Kilometres
  static double toSquareKilometres(double value) => value / 1195990.05;

  /// Converts the supplied Square Yards value to Square Metres
  static double toSquareMetres(double value) => value / 1.1959900463;

  /// Converts the supplied Square Yards value to Square Miles
  static double toSquareMiles(double value) => value / 3097600.0;

  /// Converts the supplied Square Yards value to Square Feet
  static double toSquareFeet(double value) => value * 9.0;

  /// Converts the supplied Square Yards value to Square Inches
  static double toSquareInches(double value) => value * 1296.0;

  /// Converts the supplied Square Yards value to Hectares
  static double toHectares(double value) => value / 11959.900463011;

  /// Converts the supplied Square Yards value to Acres
  static double toAcres(double value) => value / 4840.0;
}
