// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Bits {
	static double toKilobits(double value) =>
		value / 1000.0;
	static double toMegabits(double value) =>
		value / 1e+6;
	static double toGigabits(double value) =>
		value / 1e+9;
	static double toTerabits(double value) =>
		value / 1e+12;
	static double toKilobytes(double value) =>
		value / 8000.0;
	static double toMegabytes(double value) =>
		value / 8e+6;
	static double toGigabytes(double value) =>
		value / 8e+9;
	static double toTerabytes(double value) =>
		value / 8e+12;
	static double toKibibits(double value) =>
		value / 1024.0;
	static double toMebibits(double value) =>
		value / 1048576.0;
}

class Gigabits {
	static double toBits(double value) =>
		value * 1e+9;
	static double toKilobits(double value) =>
		value * 1e+6;
	static double toMegabits(double value) =>
		value * 1000.0;
	static double toTerabits(double value) =>
		value / 1000.0;
	static double toKilobytes(double value) =>
		value * 125000.0;
	static double toMegabytes(double value) =>
		value * 125.0;
	static double toGigabytes(double value) =>
		value / 8.0;
	static double toTerabytes(double value) =>
		value / 8000.0;
	static double toKibibits(double value) =>
		value * 976562.5;
	static double toMebibits(double value) =>
		value * 953.67431640625;
}

class Gigabytes {
	static double toBits(double value) =>
		value * 8e+9;
	static double toKilobits(double value) =>
		value * 8e+6;
	static double toMegabits(double value) =>
		value * 8000.0;
	static double toGigabits(double value) =>
		value * 8.0;
	static double toTerabits(double value) =>
		value / 125.0;
	static double toKilobytes(double value) =>
		value * 1e+6;
	static double toMegabytes(double value) =>
		value * 1000.0;
	static double toTerabytes(double value) =>
		value / 1000.0;
	static double toKibibits(double value) =>
		value * 7812500.0;
	static double toMebibits(double value) =>
		value * 7629.39;
}

class Kibibits {
	static double toBits(double value) =>
		value * 1024.0;
	static double toKilobits(double value) =>
		value * 1.024;
	static double toMegabits(double value) =>
		value / 976.563;
	static double toGigabits(double value) =>
		value / 976562.5;
	static double toTerabits(double value) =>
		value / 976562500.0;
	static double toKilobytes(double value) =>
		value / 7.8125;
	static double toMegabytes(double value) =>
		value / 7812.5;
	static double toGigabytes(double value) =>
		value / 7812500.0;
	static double toTerabytes(double value) =>
		value / 7812500000.0;
	static double toMebibits(double value) =>
		value / 1024.0;
}

class Kilobits {
	static double toBits(double value) =>
		value * 1000.0;
	static double toMegabits(double value) =>
		value / 1000.0;
	static double toGigabits(double value) =>
		value / 1e+6;
	static double toTerabits(double value) =>
		value / 1e+9;
	static double toKilobytes(double value) =>
		value / 8.0;
	static double toMegabytes(double value) =>
		value / 8000.0;
	static double toGigabytes(double value) =>
		value / 8e+6;
	static double toTerabytes(double value) =>
		value / 8e+9;
	static double toKibibits(double value) =>
		value / 1.024;
	static double toMebibits(double value) =>
		value / 1048.58;
}

class Kilobytes {
	static double toBits(double value) =>
		value * 8000.0;
	static double toKilobits(double value) =>
		value * 8.0;
	static double toMegabits(double value) =>
		value / 125.0;
	static double toGigabits(double value) =>
		value / 125000.0;
	static double toTerabits(double value) =>
		value / 1.25e+8;
	static double toMegabytes(double value) =>
		value / 1000.0;
	static double toGigabytes(double value) =>
		value / 1e+6;
	static double toTerabytes(double value) =>
		value / 1e+9;
	static double toKibibits(double value) =>
		value * 7.8125;
	static double toMebibits(double value) =>
		value * 0.00762939;
}

class Mebibits {
	static double toBits(double value) =>
		value * 1048576.0;
	static double toKilobits(double value) =>
		value * 1048.58;
	static double toMegabits(double value) =>
		value * 1.04858;
	static double toGigabits(double value) =>
		value / 953.67431640625;
	static double toTerabits(double value) =>
		value / 953674.0;
	static double toKilobytes(double value) =>
		value / 0.00762939;
	static double toMegabytes(double value) =>
		value / 7.62939;
	static double toGigabytes(double value) =>
		value / 7629.39;
	static double toTerabytes(double value) =>
		value * 0.000000131072;
	static double toKibibits(double value) =>
		value * 1024.0;
}

class Megabits {
	static double toBits(double value) =>
		value * 1e+6;
	static double toKilobits(double value) =>
		value * 1000.0;
	static double toGigabits(double value) =>
		value / 1000.0;
	static double toTerabits(double value) =>
		value / 1e+6;
	static double toKilobytes(double value) =>
		value * 125.0;
	static double toMegabytes(double value) =>
		value / 8.0;
	static double toGigabytes(double value) =>
		value / 8000.0;
	static double toTerabytes(double value) =>
		value / 8e+6;
	static double toKibibits(double value) =>
		value * 976.563;
	static double toMebibits(double value) =>
		value / 1.04858;
}

class Megabytes {
	static double toBits(double value) =>
		value * 8e+6;
	static double toKilobits(double value) =>
		value * 8000.0;
	static double toMegabits(double value) =>
		value * 8.0;
	static double toGigabits(double value) =>
		value / 125.0;
	static double toTerabits(double value) =>
		value / 125000.0;
	static double toKilobytes(double value) =>
		value * 1000.0;
	static double toGigabytes(double value) =>
		value / 1000.0;
	static double toTerabytes(double value) =>
		value / 1e+6;
	static double toKibibits(double value) =>
		value * 7812.5;
	static double toMebibits(double value) =>
		value * 7.62939;
}

class Terabits {
	static double toBits(double value) =>
		value * 1e+12;
	static double toKilobits(double value) =>
		value * 1e+9;
	static double toMegabits(double value) =>
		value * 1e+6;
	static double toGigabits(double value) =>
		value * 1000.0;
	static double toKilobytes(double value) =>
		value * 1.25e+8;
	static double toMegabytes(double value) =>
		value * 125000.0;
	static double toGigabytes(double value) =>
		value * 125.0;
	static double toTerabytes(double value) =>
		value / 8.0;
	static double toKibibits(double value) =>
		value * 976562500.0;
	static double toMebibits(double value) =>
		value * 953674.0;
}

class Terabytes {
	static double toBits(double value) =>
		value * 8e+12;
	static double toKilobits(double value) =>
		value * 8e+9;
	static double toMegabits(double value) =>
		value * 8e+6;
	static double toGigabits(double value) =>
		value * 8000.0;
	static double toTerabits(double value) =>
		value * 8.0;
	static double toKilobytes(double value) =>
		value * 1e+9;
	static double toMegabytes(double value) =>
		value * 1e+6;
	static double toGigabytes(double value) =>
		value * 1000.0;
	static double toKibibits(double value) =>
		value * 7812500000.0;
	static double toMebibits(double value) =>
		value / 0.000000131072;
}
