// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Btu {
	static double toKilojoules(double value) =>
		value * 1.0550559;
	static double toKilocalories(double value) =>
		value * 0.2521644007218;
	static double toJoules(double value) =>
		value * 1055.06;
	static double toCalories(double value) =>
		value * 252.1644007218;
	static double toUSTherms(double value) =>
		value / 99976.12448781215;
	static double toWattHours(double value) =>
		value * 0.293071;
	static double toKilowattHours(double value) =>
		value / 3412.14;
	static double toFootPounds(double value) =>
		value * 778.169;
	static double toElectronvolts(double value) =>
		value * 6585141385224143241216.00;
}

class Calories {
	static double toKilojoules(double value) =>
		value / 239.0057;
	static double toKilocalories(double value) =>
		value / 1000.0;
	static double toJoules(double value) =>
		value * 4.184;
	static double toBtu(double value) =>
		value / 252.1644007218;
	static double toUSTherms(double value) =>
		value / 25210420.0;
	static double toWattHours(double value) =>
		value * 0.00116222;
	static double toKilowattHours(double value) =>
		value / 860421.0;
	static double toFootPounds(double value) =>
		value * 3.08596;
	static double toElectronvolts(double value) =>
		value * 2.6131936951817e+19;
}

class Electronvolts {
	static double toKilojoules(double value) =>
		value / 6241509744511500156928.00;
	static double toKilocalories(double value) =>
		value / 26131952998320305078272.00;
	static double toJoules(double value) =>
		value / 6241509343300000000.0;
	static double toBtu(double value) =>
		value / 6585141385224143241216.0;
	static double toCalories(double value) =>
		value / 2.6131936951817e+19;
	static double toUSTherms(double value) =>
		value / 6.5835660010911e+26;
	static double toWattHours(double value) =>
		value / 2.2469422907138e+22;
	static double toKilowattHours(double value) =>
		value / 2.246943e+25;
	static double toFootPounds(double value) =>
		value / 8462350936293971968.00;
}

class FootPounds {
	static double toKilojoules(double value) =>
		value / 737.562;
	static double toKilocalories(double value) =>
		value / 3085.96;
	static double toJoules(double value) =>
		value * 1.35582;
	static double toBtu(double value) =>
		value / 778.169;
	static double toCalories(double value) =>
		value / 3.08596;
	static double toUSTherms(double value) =>
		value / 77816937.099186;
	static double toWattHours(double value) =>
		value / 2655.22;
	static double toKilowattHours(double value) =>
		value * 0.00000037662;
	static double toElectronvolts(double value) =>
		value * 8462350936293971968.00;
}

class Joules {
	static double toKilojoules(double value) =>
		value / 1000.0;
	static double toKilocalories(double value) =>
		value / 4184.0;
	static double toBtu(double value) =>
		value / 1055.06;
	static double toCalories(double value) =>
		value / 4.184;
	static double toUSTherms(double value) =>
		value / 105480400.0;
	static double toWattHours(double value) =>
		value / 3600.0;
	static double toKilowattHours(double value) =>
		value / 3.6e+6;
	static double toFootPounds(double value) =>
		value / 1.35582;
	static double toElectronvolts(double value) =>
		value * 6241509343300000000.0;
}

class Kilocalories {
	static double toKilojoules(double value) =>
		value * 4.184;
	static double toJoules(double value) =>
		value * 4184.0;
	static double toBtu(double value) =>
		value / 0.2521644007218;
	static double toCalories(double value) =>
		value * 1000.0;
	static double toUSTherms(double value) =>
		value / 25210.44007218;
	static double toWattHours(double value) =>
		value * 1.16222;
	static double toKilowattHours(double value) =>
		value / 860.421;
	static double toFootPounds(double value) =>
		value * 3085.96;
	static double toElectronvolts(double value) =>
		value * 26131952998320305078272.00;
}

class Kilojoules {
	static double toKilocalories(double value) =>
		value / 4.184;
	static double toJoules(double value) =>
		value * 1000.0;
	static double toBtu(double value) =>
		value / 1.0550559;
	static double toCalories(double value) =>
		value * 239.0057;
	static double toUSTherms(double value) =>
		value / 105480.04;
	static double toWattHours(double value) =>
		value / 3.6;
	static double toKilowattHours(double value) =>
		value / 3600.0;
	static double toFootPounds(double value) =>
		value * 737.562;
	static double toElectronvolts(double value) =>
		value * 6241509744511500156928.00;
}

class KilowattHours {
	static double toKilojoules(double value) =>
		value * 3600.0;
	static double toKilocalories(double value) =>
		value * 860.421;
	static double toJoules(double value) =>
		value * 3.6e+6;
	static double toBtu(double value) =>
		value * 3412.14;
	static double toCalories(double value) =>
		value * 860421.0;
	static double toUSTherms(double value) =>
		value / 29.3001;
	static double toWattHours(double value) =>
		value * 1000.0;
	static double toFootPounds(double value) =>
		value / 0.00000037662;
	static double toElectronvolts(double value) =>
		value * 2.246943e+25;
}

class USTherms {
	static double toKilojoules(double value) =>
		value * 105480.04;
	static double toKilocalories(double value) =>
		value * 25210.44007218;
	static double toJoules(double value) =>
		value * 105480400.0;
	static double toBtu(double value) =>
		value * 99976.12448781215;
	static double toCalories(double value) =>
		value * 25210420.0;
	static double toWattHours(double value) =>
		value * 29300.1;
	static double toKilowattHours(double value) =>
		value * 29.3001;
	static double toFootPounds(double value) =>
		value * 77816937.099186;
	static double toElectronvolts(double value) =>
		value * 6.5835660010911e+26;
}

class WattHours {
	static double toKilojoules(double value) =>
		value * 3.6;
	static double toKilocalories(double value) =>
		value / 1.16222;
	static double toJoules(double value) =>
		value * 3600.0;
	static double toBtu(double value) =>
		value / 0.293071;
	static double toCalories(double value) =>
		value / 0.00116222;
	static double toUSTherms(double value) =>
		value / 29300.1;
	static double toKilowattHours(double value) =>
		value / 1000.0;
	static double toFootPounds(double value) =>
		value * 2655.22;
	static double toElectronvolts(double value) =>
		value * 2.2469422907138e+22;
}
