// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Btu conversion functions
class Btu {
  Btu._() {}

  /// Converts the supplied Btu value to Kilojoules
  static double toKilojoules(double value) => value * 1.0550559;

  /// Converts the supplied Btu value to Kilocalories
  static double toKilocalories(double value) => value * 0.2521644007218;

  /// Converts the supplied Btu value to Joules
  static double toJoules(double value) => value * 1055.06;

  /// Converts the supplied Btu value to Calories
  static double toCalories(double value) => value * 252.1644007218;

  /// Converts the supplied Btu value to US Therms
  static double toUSTherms(double value) => value / 99976.12448781215;

  /// Converts the supplied Btu value to Watt Hours
  static double toWattHours(double value) => value * 0.293071;

  /// Converts the supplied Btu value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 3412.14;

  /// Converts the supplied Btu value to Foot Pounds
  static double toFootPounds(double value) => value * 778.169;

  /// Converts the supplied Btu value to Electronvolts
  static double toElectronvolts(double value) =>
      value * 6585141385224143241216.00;
}

/// Calories conversion functions
class Calories {
  Calories._() {}

  /// Converts the supplied Calories value to Kilojoules
  static double toKilojoules(double value) => value / 239.0057;

  /// Converts the supplied Calories value to Kilocalories
  static double toKilocalories(double value) => value / 1000.0;

  /// Converts the supplied Calories value to Joules
  static double toJoules(double value) => value * 4.184;

  /// Converts the supplied Calories value to Btu
  static double toBtu(double value) => value / 252.1644007218;

  /// Converts the supplied Calories value to US Therms
  static double toUSTherms(double value) => value / 25210420.0;

  /// Converts the supplied Calories value to Watt Hours
  static double toWattHours(double value) => value * 0.00116222;

  /// Converts the supplied Calories value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 860421.0;

  /// Converts the supplied Calories value to Foot Pounds
  static double toFootPounds(double value) => value * 3.08596;

  /// Converts the supplied Calories value to Electronvolts
  static double toElectronvolts(double value) => value * 2.6131936951817e+19;
}

/// Electronvolts conversion functions
class Electronvolts {
  Electronvolts._() {}

  /// Converts the supplied Electronvolts value to Kilojoules
  static double toKilojoules(double value) => value / 6241509744511500156928.00;

  /// Converts the supplied Electronvolts value to Kilocalories
  static double toKilocalories(double value) =>
      value / 26131952998320305078272.00;

  /// Converts the supplied Electronvolts value to Joules
  static double toJoules(double value) => value / 6241509343300000000.0;

  /// Converts the supplied Electronvolts value to Btu
  static double toBtu(double value) => value / 6585141385224143241216.0;

  /// Converts the supplied Electronvolts value to Calories
  static double toCalories(double value) => value / 2.6131936951817e+19;

  /// Converts the supplied Electronvolts value to US Therms
  static double toUSTherms(double value) => value / 6.5835660010911e+26;

  /// Converts the supplied Electronvolts value to Watt Hours
  static double toWattHours(double value) => value / 2.2469422907138e+22;

  /// Converts the supplied Electronvolts value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 2.246943e+25;

  /// Converts the supplied Electronvolts value to Foot Pounds
  static double toFootPounds(double value) => value / 8462350936293971968.00;
}

/// Foot Pounds conversion functions
class FootPounds {
  FootPounds._() {}

  /// Converts the supplied Foot Pounds value to Kilojoules
  static double toKilojoules(double value) => value / 737.562;

  /// Converts the supplied Foot Pounds value to Kilocalories
  static double toKilocalories(double value) => value / 3085.96;

  /// Converts the supplied Foot Pounds value to Joules
  static double toJoules(double value) => value * 1.35582;

  /// Converts the supplied Foot Pounds value to Btu
  static double toBtu(double value) => value / 778.169;

  /// Converts the supplied Foot Pounds value to Calories
  static double toCalories(double value) => value / 3.08596;

  /// Converts the supplied Foot Pounds value to US Therms
  static double toUSTherms(double value) => value / 77816937.099186;

  /// Converts the supplied Foot Pounds value to Watt Hours
  static double toWattHours(double value) => value / 2655.22;

  /// Converts the supplied Foot Pounds value to Kilowatt Hours
  static double toKilowattHours(double value) => value * 0.00000037662;

  /// Converts the supplied Foot Pounds value to Electronvolts
  static double toElectronvolts(double value) => value * 8462350936293971968.00;
}

/// Joules conversion functions
class Joules {
  Joules._() {}

  /// Converts the supplied Joules value to Kilojoules
  static double toKilojoules(double value) => value / 1000.0;

  /// Converts the supplied Joules value to Kilocalories
  static double toKilocalories(double value) => value / 4184.0;

  /// Converts the supplied Joules value to Btu
  static double toBtu(double value) => value / 1055.06;

  /// Converts the supplied Joules value to Calories
  static double toCalories(double value) => value / 4.184;

  /// Converts the supplied Joules value to US Therms
  static double toUSTherms(double value) => value / 105480400.0;

  /// Converts the supplied Joules value to Watt Hours
  static double toWattHours(double value) => value / 3600.0;

  /// Converts the supplied Joules value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 3.6e+6;

  /// Converts the supplied Joules value to Foot Pounds
  static double toFootPounds(double value) => value / 1.35582;

  /// Converts the supplied Joules value to Electronvolts
  static double toElectronvolts(double value) => value * 6241509343300000000.0;
}

/// Kilocalories conversion functions
class Kilocalories {
  Kilocalories._() {}

  /// Converts the supplied Kilocalories value to Kilojoules
  static double toKilojoules(double value) => value * 4.184;

  /// Converts the supplied Kilocalories value to Joules
  static double toJoules(double value) => value * 4184.0;

  /// Converts the supplied Kilocalories value to Btu
  static double toBtu(double value) => value / 0.2521644007218;

  /// Converts the supplied Kilocalories value to Calories
  static double toCalories(double value) => value * 1000.0;

  /// Converts the supplied Kilocalories value to US Therms
  static double toUSTherms(double value) => value / 25210.44007218;

  /// Converts the supplied Kilocalories value to Watt Hours
  static double toWattHours(double value) => value * 1.16222;

  /// Converts the supplied Kilocalories value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 860.421;

  /// Converts the supplied Kilocalories value to Foot Pounds
  static double toFootPounds(double value) => value * 3085.96;

  /// Converts the supplied Kilocalories value to Electronvolts
  static double toElectronvolts(double value) =>
      value * 26131952998320305078272.00;
}

/// Kilojoules conversion functions
class Kilojoules {
  Kilojoules._() {}

  /// Converts the supplied Kilojoules value to Kilocalories
  static double toKilocalories(double value) => value / 4.184;

  /// Converts the supplied Kilojoules value to Joules
  static double toJoules(double value) => value * 1000.0;

  /// Converts the supplied Kilojoules value to Btu
  static double toBtu(double value) => value / 1.0550559;

  /// Converts the supplied Kilojoules value to Calories
  static double toCalories(double value) => value * 239.0057;

  /// Converts the supplied Kilojoules value to US Therms
  static double toUSTherms(double value) => value / 105480.04;

  /// Converts the supplied Kilojoules value to Watt Hours
  static double toWattHours(double value) => value / 3.6;

  /// Converts the supplied Kilojoules value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 3600.0;

  /// Converts the supplied Kilojoules value to Foot Pounds
  static double toFootPounds(double value) => value * 737.562;

  /// Converts the supplied Kilojoules value to Electronvolts
  static double toElectronvolts(double value) =>
      value * 6241509744511500156928.00;
}

/// Kilowatt Hours conversion functions
class KilowattHours {
  KilowattHours._() {}

  /// Converts the supplied Kilowatt Hours value to Kilojoules
  static double toKilojoules(double value) => value * 3600.0;

  /// Converts the supplied Kilowatt Hours value to Kilocalories
  static double toKilocalories(double value) => value * 860.421;

  /// Converts the supplied Kilowatt Hours value to Joules
  static double toJoules(double value) => value * 3.6e+6;

  /// Converts the supplied Kilowatt Hours value to Btu
  static double toBtu(double value) => value * 3412.14;

  /// Converts the supplied Kilowatt Hours value to Calories
  static double toCalories(double value) => value * 860421.0;

  /// Converts the supplied Kilowatt Hours value to US Therms
  static double toUSTherms(double value) => value / 29.3001;

  /// Converts the supplied Kilowatt Hours value to Watt Hours
  static double toWattHours(double value) => value * 1000.0;

  /// Converts the supplied Kilowatt Hours value to Foot Pounds
  static double toFootPounds(double value) => value / 0.00000037662;

  /// Converts the supplied Kilowatt Hours value to Electronvolts
  static double toElectronvolts(double value) => value * 2.246943e+25;
}

/// US Therms conversion functions
class USTherms {
  USTherms._() {}

  /// Converts the supplied US Therms value to Kilojoules
  static double toKilojoules(double value) => value * 105480.04;

  /// Converts the supplied US Therms value to Kilocalories
  static double toKilocalories(double value) => value * 25210.44007218;

  /// Converts the supplied US Therms value to Joules
  static double toJoules(double value) => value * 105480400.0;

  /// Converts the supplied US Therms value to Btu
  static double toBtu(double value) => value * 99976.12448781215;

  /// Converts the supplied US Therms value to Calories
  static double toCalories(double value) => value * 25210420.0;

  /// Converts the supplied US Therms value to Watt Hours
  static double toWattHours(double value) => value * 29300.1;

  /// Converts the supplied US Therms value to Kilowatt Hours
  static double toKilowattHours(double value) => value * 29.3001;

  /// Converts the supplied US Therms value to Foot Pounds
  static double toFootPounds(double value) => value * 77816937.099186;

  /// Converts the supplied US Therms value to Electronvolts
  static double toElectronvolts(double value) => value * 6.5835660010911e+26;
}

/// Watt Hours conversion functions
class WattHours {
  WattHours._() {}

  /// Converts the supplied Watt Hours value to Kilojoules
  static double toKilojoules(double value) => value * 3.6;

  /// Converts the supplied Watt Hours value to Kilocalories
  static double toKilocalories(double value) => value / 1.16222;

  /// Converts the supplied Watt Hours value to Joules
  static double toJoules(double value) => value * 3600.0;

  /// Converts the supplied Watt Hours value to Btu
  static double toBtu(double value) => value / 0.293071;

  /// Converts the supplied Watt Hours value to Calories
  static double toCalories(double value) => value / 0.00116222;

  /// Converts the supplied Watt Hours value to US Therms
  static double toUSTherms(double value) => value / 29300.1;

  /// Converts the supplied Watt Hours value to Kilowatt Hours
  static double toKilowattHours(double value) => value / 1000.0;

  /// Converts the supplied Watt Hours value to Foot Pounds
  static double toFootPounds(double value) => value * 2655.22;

  /// Converts the supplied Watt Hours value to Electronvolts
  static double toElectronvolts(double value) => value * 2.2469422907138e+22;
}
