// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Dynes {
	static double toNewtons(double value) =>
		value / 100000.0;
	static double toPoundals(double value) =>
		value / 13825.4954376;
	static double toKilogramforce(double value) =>
		value / 980665.0;
}

class Kilogramforce {
	static double toNewtons(double value) =>
		value * 9.80665;
	static double toDynes(double value) =>
		value * 980665.0;
	static double toPoundals(double value) =>
		value * 70.93163528397;
}

class Newtons {
	static double toDynes(double value) =>
		value * 100000.0;
	static double toPoundals(double value) =>
		value * 7.23301;
	static double toKilogramforce(double value) =>
		value / 9.80665;
}

class Poundals {
	static double toNewtons(double value) =>
		value / 7.23301;
	static double toDynes(double value) =>
		value * 13825.4954376;
	static double toKilogramforce(double value) =>
		value / 70.93163528397;
}
