// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Gigahertz conversion functions
class Gigahertz {
  Gigahertz._() {}

  /// Converts the supplied Gigahertz value to Hertz
  static double toHertz(double value) => value * 1e+9;

  /// Converts the supplied Gigahertz value to Kilohertz
  static double toKilohertz(double value) => value * 1e+6;

  /// Converts the supplied Gigahertz value to Megahertz
  static double toMegahertz(double value) => value * 1000.0;
}

/// Hertz conversion functions
class Hertz {
  Hertz._() {}

  /// Converts the supplied Hertz value to Kilohertz
  static double toKilohertz(double value) => value / 1000.0;

  /// Converts the supplied Hertz value to Megahertz
  static double toMegahertz(double value) => value / 1e+6;

  /// Converts the supplied Hertz value to Gigahertz
  static double toGigahertz(double value) => value / 1e+9;
}

/// Kilohertz conversion functions
class Kilohertz {
  Kilohertz._() {}

  /// Converts the supplied Kilohertz value to Hertz
  static double toHertz(double value) => value * 1000.0;

  /// Converts the supplied Kilohertz value to Megahertz
  static double toMegahertz(double value) => value / 1000.0;

  /// Converts the supplied Kilohertz value to Gigahertz
  static double toGigahertz(double value) => value / 1e+6;
}

/// Megahertz conversion functions
class Megahertz {
  Megahertz._() {}

  /// Converts the supplied Megahertz value to Hertz
  static double toHertz(double value) => value * 1e+6;

  /// Converts the supplied Megahertz value to Kilohertz
  static double toKilohertz(double value) => value * 1000.0;

  /// Converts the supplied Megahertz value to Gigahertz
  static double toGigahertz(double value) => value / 1000.0;
}
