// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Ampereturns {
	static double toGilberts(double value) =>
		value / 0.7957747154595;
}

class Gilberts {
	static double toAmpereturns(double value) =>
		value * 0.7957747154595;
}
