// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Carats {
	static double toMilligrams(double value) =>
		value * 200.0;
	static double toGrams(double value) =>
		value / 5.0;
	static double toKilograms(double value) =>
		value / 5000.0;
	static double toTonnes(double value) =>
		value / 5e+6;
	static double toOunces(double value) =>
		value * 0.00705479;
	static double toPounds(double value) =>
		value * 0.000440925;
	static double toStones(double value) =>
		value * 3.1495e-5;
}

class Grams {
	static double toMilligrams(double value) =>
		value * 1000.0;
	static double toKilograms(double value) =>
		value / 1000.0;
	static double toTonnes(double value) =>
		value * 1e-6;
	static double toOunces(double value) =>
		value / 28.3495231;
	static double toPounds(double value) =>
		value / 453.59237;
	static double toStones(double value) =>
		value / 6350.29318;
	static double toCarats(double value) =>
		value * 5.0;
}

class Kilograms {
	static double toMilligrams(double value) =>
		value * 1e+6;
	static double toGrams(double value) =>
		value * 1000.0;
	static double toTonnes(double value) =>
		value * 0.001;
	static double toOunces(double value) =>
		value * 35.274;
	static double toPounds(double value) =>
		value * 2.20462;
	static double toStones(double value) =>
		value / 6.35029;
	static double toCarats(double value) =>
		value * 5000.0;
}

class Milligrams {
	static double toGrams(double value) =>
		value / 1000.0;
	static double toKilograms(double value) =>
		value / 1e+6;
	static double toTonnes(double value) =>
		value / 1e+9;
	static double toOunces(double value) =>
		value / 28349.5231;
	static double toPounds(double value) =>
		value / 453592.37;
	static double toStones(double value) =>
		value / 6350293.18;
	static double toCarats(double value) =>
		value / 200.0;
}

class Ounces {
	static double toMilligrams(double value) =>
		value * 28349.5231;
	static double toGrams(double value) =>
		value * 28.3495231;
	static double toKilograms(double value) =>
		value / 35.274;
	static double toTonnes(double value) =>
		value * 0.0000283495231;
	static double toPounds(double value) =>
		value * 0.0625;
	static double toStones(double value) =>
		value / 224.0;
	static double toCarats(double value) =>
		value / 0.00705479;
}

class Pounds {
	static double toMilligrams(double value) =>
		value * 453592.37;
	static double toGrams(double value) =>
		value * 453.59237;
	static double toKilograms(double value) =>
		value / 2.20462;
	static double toTonnes(double value) =>
		value / 2204.62;
	static double toOunces(double value) =>
		value * 16.0;
	static double toStones(double value) =>
		value / 14.0;
	static double toCarats(double value) =>
		value / 0.000440925;
}

class Stones {
	static double toMilligrams(double value) =>
		value * 6350293.18;
	static double toGrams(double value) =>
		value * 6350.29318;
	static double toKilograms(double value) =>
		value * 6.35029;
	static double toTonnes(double value) =>
		value / 157.473;
	static double toOunces(double value) =>
		value * 224.0;
	static double toPounds(double value) =>
		value * 14.0;
	static double toCarats(double value) =>
		value / 3.1495e-5;
}

class Tonnes {
	static double toMilligrams(double value) =>
		value * 1e+9;
	static double toGrams(double value) =>
		value * 1e+6;
	static double toKilograms(double value) =>
		value * 1000.0;
	static double toOunces(double value) =>
		value / 0.0000283495231;
	static double toPounds(double value) =>
		value * 2204.62;
	static double toStones(double value) =>
		value * 157.473;
	static double toCarats(double value) =>
		value * 5e+6;
}
