// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Mechanical Horse Power conversion functions
class MechanicalHorsePower {
  MechanicalHorsePower._() {}

  /// Converts the supplied Mechanical Horse Power value to Metric Horse Power
  static double toMetricHorsePower(double value) => value * 1.013869665424;
}

/// Metric Horse Power conversion functions
class MetricHorsePower {
  MetricHorsePower._() {}

  /// Converts the supplied Metric Horse Power value to Mechanical Horse Power
  static double toMechanicalHorsePower(double value) => value / 1.013869665424;
}
