// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Atmospheres {
	static double toBars(double value) =>
		value * 1.01325;
	static double toPascals(double value) =>
		value * 101325.0;
	static double toTorrs(double value) =>
		value * 760.0;
	static double toPsi(double value) =>
		value * 14.69596432068;
}

class Bars {
	static double toAtmospheres(double value) =>
		value / 1.01325;
	static double toPascals(double value) =>
		value / 0.00001;
	static double toTorrs(double value) =>
		value * 750.0616827042;
	static double toPsi(double value) =>
		value * 14.50378911491;
}

class Pascals {
	static double toAtmospheres(double value) =>
		value / 101325.0;
	static double toBars(double value) =>
		value * 0.00001;
	static double toTorrs(double value) =>
		value * 0.007500616827042;
	static double toPsi(double value) =>
		value * 0.0001450378911491;
}

class Psi {
	static double toBars(double value) =>
		value / 14.50378911491;
	static double toPascals(double value) =>
		value / 0.0001450378911491;
	static double toAtmospheres(double value) =>
		value / 14.69596432068;
	static double toTorrs(double value) =>
		value / 0.01933679515879;
}

class Torrs {
	static double toBars(double value) =>
		value / 750.0616827042;
	static double toPascals(double value) =>
		value / 0.007500616827042;
	static double toAtmospheres(double value) =>
		value / 760.0;
	static double toPsi(double value) =>
		value * 0.01933679515879;
}
