// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class FeetPerSecond {
	static double toMilesPerHour(double value) =>
		value / 1.46667;
	static double toKilometresPerHour(double value) =>
		value * 1.09728;
	static double toMetresPerSecond(double value) =>
		value / 3.28084;
	static double toKnots(double value) =>
		value / 1.68781;
}

class KilometresPerHour {
	static double toMilesPerHour(double value) =>
		value / 1.60934;
	static double toFeetPerSecond(double value) =>
		value / 1.09728;
	static double toMetresPerSecond(double value) =>
		value / 3.6;
	static double toKnots(double value) =>
		value / 1.852;
}

class Knots {
	static double toMilesPerHour(double value) =>
		value * 1.15078;
	static double toKilometresPerHour(double value) =>
		value * 1.852;
	static double toFeetPerSecond(double value) =>
		value * 1.68781;
	static double toMetresPerSecond(double value) =>
		value / 1.94384;
}

class MetresPerSecond {
	static double toMilesPerHour(double value) =>
		value * 2.23694;
	static double toKilometresPerHour(double value) =>
		value * 3.6;
	static double toFeetPerSecond(double value) =>
		value * 3.28084;
	static double toKnots(double value) =>
		value * 1.94384;
}

class MilesPerHour {
	static double toKilometresPerHour(double value) =>
		value * 1.60934;
	static double toFeetPerSecond(double value) =>
		value * 1.46667;
	static double toMetresPerSecond(double value) =>
		value / 2.23694;
	static double toKnots(double value) =>
		value / 1.15078;
}
