// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Feet Per Second conversion functions
class FeetPerSecond {
  FeetPerSecond._() {}

  /// Converts the supplied Feet Per Second value to Miles Per Hour
  static double toMilesPerHour(double value) => value / 1.46667;

  /// Converts the supplied Feet Per Second value to Kilometres Per Hour
  static double toKilometresPerHour(double value) => value * 1.09728;

  /// Converts the supplied Feet Per Second value to Metres Per Second
  static double toMetresPerSecond(double value) => value / 3.28084;

  /// Converts the supplied Feet Per Second value to Knots
  static double toKnots(double value) => value / 1.68781;
}

/// Kilometres Per Hour conversion functions
class KilometresPerHour {
  KilometresPerHour._() {}

  /// Converts the supplied Kilometres Per Hour value to Miles Per Hour
  static double toMilesPerHour(double value) => value / 1.60934;

  /// Converts the supplied Kilometres Per Hour value to Feet Per Second
  static double toFeetPerSecond(double value) => value / 1.09728;

  /// Converts the supplied Kilometres Per Hour value to Metres Per Second
  static double toMetresPerSecond(double value) => value / 3.6;

  /// Converts the supplied Kilometres Per Hour value to Knots
  static double toKnots(double value) => value / 1.852;
}

/// Knots conversion functions
class Knots {
  Knots._() {}

  /// Converts the supplied Knots value to Miles Per Hour
  static double toMilesPerHour(double value) => value * 1.15078;

  /// Converts the supplied Knots value to Kilometres Per Hour
  static double toKilometresPerHour(double value) => value * 1.852;

  /// Converts the supplied Knots value to Feet Per Second
  static double toFeetPerSecond(double value) => value * 1.68781;

  /// Converts the supplied Knots value to Metres Per Second
  static double toMetresPerSecond(double value) => value / 1.94384;
}

/// Metres Per Second conversion functions
class MetresPerSecond {
  MetresPerSecond._() {}

  /// Converts the supplied Metres Per Second value to Miles Per Hour
  static double toMilesPerHour(double value) => value * 2.23694;

  /// Converts the supplied Metres Per Second value to Kilometres Per Hour
  static double toKilometresPerHour(double value) => value * 3.6;

  /// Converts the supplied Metres Per Second value to Feet Per Second
  static double toFeetPerSecond(double value) => value * 3.28084;

  /// Converts the supplied Metres Per Second value to Knots
  static double toKnots(double value) => value * 1.94384;
}

/// Miles Per Hour conversion functions
class MilesPerHour {
  MilesPerHour._() {}

  /// Converts the supplied Miles Per Hour value to Kilometres Per Hour
  static double toKilometresPerHour(double value) => value * 1.60934;

  /// Converts the supplied Miles Per Hour value to Feet Per Second
  static double toFeetPerSecond(double value) => value * 1.46667;

  /// Converts the supplied Miles Per Hour value to Metres Per Second
  static double toMetresPerSecond(double value) => value / 2.23694;

  /// Converts the supplied Miles Per Hour value to Knots
  static double toKnots(double value) => value / 1.15078;
}
