// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class Centuries {
	static double toSeconds(double value) =>
		value * 3.154e+9;
	static double toMinutes(double value) =>
		value * 5.256e+7;
	static double toHours(double value) =>
		value * 876000.0;
	static double toDays(double value) =>
		value * 36500.0;
	static double toWeeks(double value) =>
		value * 5214.29;
	static double toMonths(double value) =>
		value * 1200.0;
	static double toYears(double value) =>
		value * 100.0;
	static double toDecades(double value) =>
		value * 10.0;
}

class Days {
	static double toSeconds(double value) =>
		value * 86400.0;
	static double toMinutes(double value) =>
		value * 1440.0;
	static double toHours(double value) =>
		value * 24.0;
	static double toWeeks(double value) =>
		value / 7.0;
	static double toMonths(double value) =>
		value / 30.4167;
	static double toYears(double value) =>
		value / 365.0;
	static double toDecades(double value) =>
		value / 3650.0;
	static double toCenturies(double value) =>
		value / 36500.0;
}

class Decades {
	static double toSeconds(double value) =>
		value * 3.154e+8;
	static double toMinutes(double value) =>
		value * 5.256e+6;
	static double toHours(double value) =>
		value * 87600.0;
	static double toDays(double value) =>
		value * 3650.0;
	static double toWeeks(double value) =>
		value * 521.429;
	static double toMonths(double value) =>
		value * 120.0;
	static double toYears(double value) =>
		value * 10.0;
	static double toCenturies(double value) =>
		value / 10.0;
}

class Hours {
	static double toSeconds(double value) =>
		value * 3600.0;
	static double toMinutes(double value) =>
		value * 60.0;
	static double toDays(double value) =>
		value / 24.0;
	static double toWeeks(double value) =>
		value / 168.0;
	static double toMonths(double value) =>
		value / 730.001;
	static double toYears(double value) =>
		value / 8760.0;
	static double toDecades(double value) =>
		value / 87600.0;
	static double toCenturies(double value) =>
		value / 876000.0;
}

class Minutes {
	static double toSeconds(double value) =>
		value * 60.0;
	static double toHours(double value) =>
		value / 60.0;
	static double toDays(double value) =>
		value / 1440.0;
	static double toWeeks(double value) =>
		value / 10080.0;
	static double toMonths(double value) =>
		value / 43800.0;
	static double toYears(double value) =>
		value / 525600.0;
	static double toDecades(double value) =>
		value / 5.256e+6;
	static double toCenturies(double value) =>
		value / 5.256e+7;
}

class Months {
	static double toSeconds(double value) =>
		value * 2.628e+6;
	static double toMinutes(double value) =>
		value * 43800.0;
	static double toHours(double value) =>
		value * 730.001;
	static double toDays(double value) =>
		value * 30.4167;
	static double toWeeks(double value) =>
		value * 4.34524;
	static double toYears(double value) =>
		value / 12.0;
	static double toDecades(double value) =>
		value / 120.0;
	static double toCenturies(double value) =>
		value / 1200.0;
}

class Seconds {
	static double toMinutes(double value) =>
		value / 60.0;
	static double toHours(double value) =>
		value / 3600.0;
	static double toDays(double value) =>
		value / 86400.0;
	static double toWeeks(double value) =>
		value / 604800.0;
	static double toMonths(double value) =>
		value / 2.628e+6;
	static double toYears(double value) =>
		value / 3.1536e+7;
	static double toDecades(double value) =>
		value / 3.154e+8;
	static double toCenturies(double value) =>
		value / 3.154e+9;
}

class Weeks {
	static double toSeconds(double value) =>
		value * 604800.0;
	static double toMinutes(double value) =>
		value * 10080.0;
	static double toHours(double value) =>
		value * 168.0;
	static double toDays(double value) =>
		value * 7.0;
	static double toMonths(double value) =>
		value / 4.34524;
	static double toYears(double value) =>
		value / 52.143;
	static double toDecades(double value) =>
		value / 521.429;
	static double toCenturies(double value) =>
		value / 5214.29;
}

class Years {
	static double toSeconds(double value) =>
		value * 3.1536e+7;
	static double toMinutes(double value) =>
		value * 525600.0;
	static double toHours(double value) =>
		value * 8760.0;
	static double toDays(double value) =>
		value * 365.0;
	static double toWeeks(double value) =>
		value * 52.143;
	static double toMonths(double value) =>
		value * 12.0;
	static double toDecades(double value) =>
		value / 10.0;
	static double toCenturies(double value) =>
		value / 100.0;
}
