// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

class FluidOunces {
	static double toMillilitres(double value) =>
		value * 28.413074243749994496;
	static double toLitres(double value) =>
		value * 0.028413074243749994496;
	static double toKilolitres(double value) =>
		value * 0.000028413074243749994;
	static double toTeaspoons(double value) =>
		value * 4.8;
	static double toTablespoons(double value) =>
		value * 1.6;
	static double toQuarts(double value) =>
		value / 40.0;
	static double toPints(double value) =>
		value / 20.0;
	static double toGallons(double value) =>
		value / 160.0;
	static double toUSTeaspoons(double value) =>
		value / 0.1734737167638313984;
	static double toUSTablespoons(double value) =>
		value / 0.52042115029149417472;
	static double toUSQuarts(double value) =>
		value / 33.306953618655629312;
	static double toUSPints(double value) =>
		value / 16.653476809327814656;
	static double toUSGallons(double value) =>
		value / 133.22781447462252544;
	static double toUSFluidOunces(double value) =>
		value / 1.0408423005829883904;
	static double toUSCups(double value) =>
		value / 8.3267384046639071232;
}

class Gallons {
	static double toMillilitres(double value) =>
		value * 4546.091879;
	static double toLitres(double value) =>
		value * 4.546091879;
	static double toKilolitres(double value) =>
		value * 0.0045460918799;
	static double toTeaspoons(double value) =>
		value * 768.0;
	static double toTablespoons(double value) =>
		value * 256.0;
	static double toQuarts(double value) =>
		value * 4.0;
	static double toPints(double value) =>
		value * 8.0;
	static double toFluidOunces(double value) =>
		value * 160.0;
	static double toUSTeaspoons(double value) =>
		value / 0.00108421072977394606;
	static double toUSTablespoons(double value) =>
		value / 0.003252632189321838592;
	static double toUSQuarts(double value) =>
		value / 0.20816846011659767808;
	static double toUSPints(double value) =>
		value / 0.10408423005829883904;
	static double toUSGallons(double value) =>
		value / 0.83267384046639071232;
	static double toUSFluidOunces(double value) =>
		value / 0.006505264378643677184;
	static double toUSCups(double value) =>
		value / 0.052042115029149417472;
}

class Kilolitres {
	static double toMillilitres(double value) =>
		value * 1000000.0;
	static double toLitres(double value) =>
		value * 1000.0;
	static double toTeaspoons(double value) =>
		value / 0.000005919390467447916;
	static double toTablespoons(double value) =>
		value / 0.000017758171402343747;
	static double toQuarts(double value) =>
		value / 0.00113652296975;
	static double toPints(double value) =>
		value / 0.000568261484874999889;
	static double toGallons(double value) =>
		value / 0.0045460918799;
	static double toFluidOunces(double value) =>
		value / 0.0000284130742437499946;
	static double toUSTeaspoons(double value) =>
		value / 0.000004928921593749999;
	static double toUSTablespoons(double value) =>
		value / 0.000014786764781249998;
	static double toUSQuarts(double value) =>
		value / 0.000946352945999999959;
	static double toUSPints(double value) =>
		value / 0.000473176472999999979;
	static double toUSGallons(double value) =>
		value / 0.003785411784;
	static double toUSFluidOunces(double value) =>
		value / 0.0000295735296;
	static double toUSCups(double value) =>
		value / 0.000236588236499999989;
}

class Litres {
	static double toMillilitres(double value) =>
		value * 1000.0;
	static double toKilolitres(double value) =>
		value / 1000.0;
	static double toTeaspoons(double value) =>
		value / 0.005919390467447916134;
	static double toTablespoons(double value) =>
		value / 0.017758171402343747584;
	static double toQuarts(double value) =>
		value / 1.13652296975;
	static double toPints(double value) =>
		value / 0.56826148487499988992;
	static double toGallons(double value) =>
		value / 4.546091879;
	static double toFluidOunces(double value) =>
		value / 0.028413074243749994496;
	static double toUSTeaspoons(double value) =>
		value / 0.004928921593749999616;
	static double toUSTablespoons(double value) =>
		value / 0.014786764781249998848;
	static double toUSQuarts(double value) =>
		value / 0.94635294599999995904;
	static double toUSPints(double value) =>
		value / 0.47317647299999997952;
	static double toUSGallons(double value) =>
		value / 3.785411784;
	static double toUSFluidOunces(double value) =>
		value / 0.029573529562499997696;
	static double toUSCups(double value) =>
		value / 0.23658823649999998976;
}

class Millilitres {
	static double toLitres(double value) =>
		value / 1000.0;
	static double toKilolitres(double value) =>
		value / 1000000.0;
	static double toTeaspoons(double value) =>
		value / 5.9193904674479161344;
	static double toTablespoons(double value) =>
		value / 17.758171402343747584;
	static double toQuarts(double value) =>
		value / 1136.52296975;
	static double toPints(double value) =>
		value / 568.26148487499988992;
	static double toGallons(double value) =>
		value / 4546.091879;
	static double toFluidOunces(double value) =>
		value / 28.413074243749994496;
	static double toUSTeaspoons(double value) =>
		value / 4.928921593749999616;
	static double toUSTablespoons(double value) =>
		value / 14.786764781249998848;
	static double toUSQuarts(double value) =>
		value / 946.35294599999995904;
	static double toUSPints(double value) =>
		value / 473.17647299999997952;
	static double toUSGallons(double value) =>
		value / 3785.411784;
	static double toUSFluidOunces(double value) =>
		value / 29.573529562499997696;
	static double toUSCups(double value) =>
		value / 236.58823649999998976;
}

class Pints {
	static double toMillilitres(double value) =>
		value * 568.26148487499988992;
	static double toLitres(double value) =>
		value * 0.56826148487499988992;
	static double toKilolitres(double value) =>
		value * 0.000568261484874999889;
	static double toTeaspoons(double value) =>
		value * 96.0;
	static double toTablespoons(double value) =>
		value * 32.0;
	static double toQuarts(double value) =>
		value  / 2.0;
	static double toGallons(double value) =>
		value / 8.0;
	static double toFluidOunces(double value) =>
		value * 20.0;
	static double toUSTeaspoons(double value) =>
		value / 0.008673685838191568486;
	static double toUSTablespoons(double value) =>
		value / 0.026021057514574708736;
	static double toUSQuarts(double value) =>
		value / 1.6653476809327814656;
	static double toUSPints(double value) =>
		value / 0.83267384046639071232;
	static double toUSGallons(double value) =>
		value / 6.6613907237311258624;
	static double toUSFluidOunces(double value) =>
		value / 0.052042115029149417472;
	static double toUSCups(double value) =>
		value / 0.41633692023319535616;
}

class Quarts {
	static double toMillilitres(double value) =>
		value * 1136.52296975;
	static double toLitres(double value) =>
		value * 1.13652296975;
	static double toKilolitres(double value) =>
		value * 0.00113652296975;
	static double toTeaspoons(double value) =>
		value * 192.0;
	static double toTablespoons(double value) =>
		value * 64.0;
	static double toPints(double value) =>
		value * 2.0;
	static double toGallons(double value) =>
		value / 4.0;
	static double toFluidOunces(double value) =>
		value * 40.0;
	static double toUSTeaspoons(double value) =>
		value / 0.004336842919095784243;
	static double toUSTablespoons(double value) =>
		value / 0.013010528757287354368;
	static double toUSQuarts(double value) =>
		value / 0.83267384046639071232;
	static double toUSPints(double value) =>
		value / 0.41633692023319535616;
	static double toUSGallons(double value) =>
		value / 3.3306953618655629312;
	static double toUSFluidOunces(double value) =>
		value / 0.026021057514574708736;
	static double toUSCups(double value) =>
		value / 0.20816846011659767808;
}

class Tablespoons {
	static double toMillilitres(double value) =>
		value * 17.758171402343747584;
	static double toLitres(double value) =>
		value * 0.017758171402343747584;
	static double toKilolitres(double value) =>
		value * 0.000017758171402343747;
	static double toTeaspoons(double value) =>
		value * 3.0;
	static double toQuarts(double value) =>
		value / 64.0;
	static double toPints(double value) =>
		value / 32.0;
	static double toGallons(double value) =>
		value / 256.0;
	static double toFluidOunces(double value) =>
		value / 1.6;
	static double toUSTeaspoons(double value) =>
		value / 0.27755794682213023744;
	static double toUSTablespoons(double value) =>
		value / 0.83267384046639071232;
	static double toUSQuarts(double value) =>
		value / 53.291125789849001984;
	static double toUSPints(double value) =>
		value / 26.645562894924500992;
	static double toUSGallons(double value) =>
		value / 213.16450315939602432;
	static double toUSFluidOunces(double value) =>
		value / 1.6653476809327814656;
	static double toUSCups(double value) =>
		value / 13.322781447462250496;
}

class Teaspoons {
	static double toMillilitres(double value) =>
		value * 5.9193904674479161344;
	static double toLitres(double value) =>
		value * 0.005919390467447916134;
	static double toKilolitres(double value) =>
		value * 0.000005919390467447916;
	static double toTablespoons(double value) =>
		value / 3.0;
	static double toQuarts(double value) =>
		value / 192.0;
	static double toPints(double value) =>
		value / 96.0;
	static double toGallons(double value) =>
		value / 768.0;
	static double toFluidOunces(double value) =>
		value / 4.8;
	static double toUSTeaspoons(double value) =>
		value / 0.83267384046639071232;
	static double toUSTablespoons(double value) =>
		value / 2.4980215213991718912;
	static double toUSQuarts(double value) =>
		value / 159.87337736954701824;
	static double toUSPints(double value) =>
		value / 79.936688684773507072;
	static double toUSGallons(double value) =>
		value / 639.49350947818807296;
	static double toUSFluidOunces(double value) =>
		value / 4.9960430427983437824;
	static double toUSCups(double value) =>
		value / 39.968344342386753536;
}

class USCups {
	static double toMillilitres(double value) =>
		value * 236.58823649999998976;
	static double toLitres(double value) =>
		value * 0.23658823649999998976;
	static double toKilolitres(double value) =>
		value * 0.000236588236499999989;
	static double toTeaspoons(double value) =>
		value * 39.968344342386753536;
	static double toTablespoons(double value) =>
		value * 13.322781447462250496;
	static double toQuarts(double value) =>
		value * 0.20816846011659767808;
	static double toPints(double value) =>
		value * 0.41633692023319535616;
	static double toGallons(double value) =>
		value * 0.052042115029149417472;
	static double toFluidOunces(double value) =>
		value * 8.3267384046639071232;
	static double toUSTeaspoons(double value) =>
		value * 48.0;
	static double toUSTablespoons(double value) =>
		value * 16.0;
	static double toUSQuarts(double value) =>
		value / 4.0;
	static double toUSPints(double value) =>
		value / 2.0;
	static double toUSGallons(double value) =>
		value / 16.0;
	static double toUSFluidOunces(double value) =>
		value * 8.0;
}

class USFluidOunces {
	static double toMillilitres(double value) =>
		value * 29.573529562499997696;
	static double toLitres(double value) =>
		value * 0.029573529562499997696;
	static double toKilolitres(double value) =>
		value * 0.0000295735296;
	static double toTeaspoons(double value) =>
		value * 4.9960430427983437824;
	static double toTablespoons(double value) =>
		value * 1.6653476809327814656;
	static double toQuarts(double value) =>
		value * 0.026021057514574708736;
	static double toPints(double value) =>
		value * 0.052042115029149417472;
	static double toGallons(double value) =>
		value * 0.006505264378643677184;
	static double toFluidOunces(double value) =>
		value * 1.0408423005829883904;
	static double toUSTeaspoons(double value) =>
		value * 6.0;
	static double toUSTablespoons(double value) =>
		value * 2.0;
	static double toUSQuarts(double value) =>
		value / 32.0;
	static double toUSPints(double value) =>
		value / 16.0;
	static double toUSGallons(double value) =>
		value / 128.0;
	static double toUSCups(double value) =>
		value / 8.0;
}

class USGallons {
	static double toMillilitres(double value) =>
		value * 3785.411784;
	static double toLitres(double value) =>
		value * 3.785411784;
	static double toKilolitres(double value) =>
		value * 0.003785411784;
	static double toTeaspoons(double value) =>
		value * 639.49350947818807296;
	static double toTablespoons(double value) =>
		value * 213.16450315939602432;
	static double toQuarts(double value) =>
		value * 3.3306953618655629312;
	static double toPints(double value) =>
		value * 6.6613907237311258624;
	static double toGallons(double value) =>
		value * 0.83267384046639071232;
	static double toFluidOunces(double value) =>
		value * 133.22781447462252544;
	static double toUSTeaspoons(double value) =>
		value * 768.0;
	static double toUSTablespoons(double value) =>
		value * 256.0;
	static double toUSQuarts(double value) =>
		value * 4.0;
	static double toUSPints(double value) =>
		value * 8.0;
	static double toUSFluidOunces(double value) =>
		value * 128.0;
	static double toUSCups(double value) =>
		value * 16.0;
}

class USPints {
	static double toMillilitres(double value) =>
		value * 473.17647299999997952;
	static double toLitres(double value) =>
		value * 0.47317647299999997952;
	static double toKilolitres(double value) =>
		value * 0.000473176472999999979;
	static double toTeaspoons(double value) =>
		value * 79.936688684773507072;
	static double toTablespoons(double value) =>
		value * 26.645562894924500992;
	static double toQuarts(double value) =>
		value * 0.41633692023319535616;
	static double toPints(double value) =>
		value * 0.83267384046639071232;
	static double toGallons(double value) =>
		value * 0.10408423005829883904;
	static double toFluidOunces(double value) =>
		value * 16.653476809327814656;
	static double toUSTeaspoons(double value) =>
		value * 96.0;
	static double toUSTablespoons(double value) =>
		value * 32.0;
	static double toUSQuarts(double value) =>
		value / 2.0;
	static double toUSGallons(double value) =>
		value / 8.0;
	static double toUSFluidOunces(double value) =>
		value * 16.0;
	static double toUSCups(double value) =>
		value * 2.0;
}

class USQuarts {
	static double toMillilitres(double value) =>
		value * 946.35294599999995904;
	static double toLitres(double value) =>
		value * 0.94635294599999995904;
	static double toKilolitres(double value) =>
		value * 0.000946352945999999959;
	static double toTeaspoons(double value) =>
		value * 159.87337736954701824;
	static double toTablespoons(double value) =>
		value * 53.291125789849001984;
	static double toQuarts(double value) =>
		value * 0.83267384046639071232;
	static double toPints(double value) =>
		value * 1.6653476809327814656;
	static double toGallons(double value) =>
		value * 0.20816846011659767808;
	static double toFluidOunces(double value) =>
		value * 33.306953618655629312;
	static double toUSTeaspoons(double value) =>
		value * 192.0;
	static double toUSTablespoons(double value) =>
		value * 64.0;
	static double toUSPints(double value) =>
		value * 2.0;
	static double toUSGallons(double value) =>
		value / 4.0;
	static double toUSFluidOunces(double value) =>
		value * 32.0;
	static double toUSCups(double value) =>
		value * 4.0;
}

class USTablespoons {
	static double toMillilitres(double value) =>
		value * 14.786764781249998848;
	static double toLitres(double value) =>
		value * 0.014786764781249998848;
	static double toKilolitres(double value) =>
		value * 0.000014786764781249998;
	static double toTeaspoons(double value) =>
		value * 2.4980215213991718912;
	static double toTablespoons(double value) =>
		value * 0.83267384046639071232;
	static double toQuarts(double value) =>
		value * 0.013010528757287354368;
	static double toPints(double value) =>
		value * 0.026021057514574708736;
	static double toGallons(double value) =>
		value * 0.003252632189321838592;
	static double toFluidOunces(double value) =>
		value * 0.52042115029149417472;
	static double toUSTeaspoons(double value) =>
		value * 3.0;
	static double toUSQuarts(double value) =>
		value / 64.0;
	static double toUSPints(double value) =>
		value / 32.0;
	static double toUSGallons(double value) =>
		value / 256.0;
	static double toUSFluidOunces(double value) =>
		value / 2.0;
	static double toUSCups(double value) =>
		value / 16.0;
}

class USTeaspoons {
	static double toMillilitres(double value) =>
		value * 4.928921593749999616;
	static double toLitres(double value) =>
		value * 0.004928921593749999616;
	static double toKilolitres(double value) =>
		value * 0.000004928921593749999;
	static double toTeaspoons(double value) =>
		value * 0.83267384046639071232;
	static double toTablespoons(double value) =>
		value * 0.27755794682213023744;
	static double toQuarts(double value) =>
		value * 0.004336842919095784243;
	static double toPints(double value) =>
		value * 0.008673685838191568486;
	static double toGallons(double value) =>
		value * 0.00108421072977394606;
	static double toFluidOunces(double value) =>
		value * 0.1734737167638313984;
	static double toUSTablespoons(double value) =>
		value / 3.0;
	static double toUSQuarts(double value) =>
		value / 192.0;
	static double toUSPints(double value) =>
		value / 96.0;
	static double toUSGallons(double value) =>
		value / 768.0;
	static double toUSFluidOunces(double value) =>
		value / 6.0;
	static double toUSCups(double value) =>
		value / 48.0;
}
